### ISSUE TITLE
Binary body data in hapi response

### ISSUE THREAD

**Issue by marioosh-net** [hapijs/hapi#1493]
Hello again,

I have a problem. I make request using [request](https://github.com/mikeal/request) in handler function and get response body, exactly pdf file. How to show this pdf using hapi reponse ? I did like below, but it doesn't work.

```
var request2 = require('request');
...
var pdf = function(request, reply) {
    var json = [];
    json.push(parseInt(request.params.id));
    request2({
        url: '...',
        method: 'POST',
        body: JSON.stringify(json),
        headers: { ... }        
    }, function(err, message, body){
        if(err) {
            throw err;
        }
        reply(body).bytes(body.length).type('application/pdf');
    });
};
```

PS: sorry, if github is not right place to ask questions like that.

**Comment by darkua** [comment]
Hello, im having a issue with replying a pdf file... 

tried:
reply(body).bytes(body.length).type('application/pdf');
reply.file("filename.pdf")

and browser fails to be able to view the file, it seems a encoding issue because when set up as attachment and checking the difference not same content.  ( %PDF-1.4 %áéëÓ vs %PDF-1.4 %���� )

Any idea, what can be wrong?

thanks

**Comment by llonchj** [comment]
@darkua +1 looks like encoding, showing latin-1 vs utf-8 characters. Someone knows if hapi does some post process on response body?
