### ISSUE TITLE
HowTo: Send multiple data in reply

### ISSUE THREAD

**Issue by chetandhembre** [hapijs/hapi#1706]
I am want to send data multiple time before closing http connection. Like if i am want to do it in simple node.js code .. i will call `res.write('demo')` then `res.write('demo1')` and finally `res.end('demo2')`. Client will get following output

```
demo
demo1
demo2
```

How can i achieve this in hapi ? am i missing something here ?

**Comment by ItsAsbreuk** [comment]
I ran into the same issue.

It is a client-side issue, though it seems you do have to set the `Transfer-Encoding`-header to `chunked`, otherwise a content-length of `9` is taken.

Some browsers only start to use streaming when a certain amount of bytes are received. Only once the amount of bytes comes above a certain limit, the browsers starts streaming. If below, they wait for all the data to be received and handle it at once.

The data-limit differs per browser: 
Chrome 43.0.2357.81 and Opera 29.0: *buffer 2kb* 
Safari 8.0.6: *buffers 1kb*
IE9 and FF 38.0.1: stream right away

Even more interesting, specifying the `Content-Type` changes this behaviour.
The above findings were without a content-type specified (leading to `text/plain; charset=UTF-8`, however:

`text/html; charset=UTF-8`:
Chrome and Opera: stream right away 
Safari: *buffers 1kb*
IE and FF stream right away

`application.json; charset=UTF-8`:
Chrome and Opera: stream right away 
Safari: streams right away 
IE and FF: stream right away
