### ISSUE TITLE
Multiple paths for views

### ISSUE THREAD

**Issue by imjoshholloway** [hapijs/hapi#1753]
Is there anyway to have multiple paths setup for views?

E.g;

```
plugin.views({
    path: [__dirname + "/templates, __dirname + "/../templates"]
});
```

**Comment by sonisaurabh19** [comment]
Hi, can anyone kindly tell how the usage shall be? 
I tried like mentioned above with fail - path: [__dirname + "/templates", __dirname + "/../templates"]
Thanks.

**Comment by mtharrison** [comment]
@sonisaurabh19 that works for me:
```javascript
server.views({
    engines: { hbs: require('handlebars') },
    path: [__dirname + "/templates", __dirname + "/../templates"]
});
```

 What's the error you're seeing?

**Comment by sonisaurabh19** [comment]
I have a server/views/ directory wherein all the jade files are present. Since my case is now beginning to have more jade files, I thought of structuring server/views/ based on actors. Something like:
Ex - server/views/admin/task1.jade
Ex - server/views/superadmin/task2.jade

My index.js looks like:
server.views({
	engines: 
	{
	    jade: require('jade') 
	},
        path: [ __dirname + "/app/server/views/admin", __dirname + "/app/server/views/superadmin" ]
});

With the above configuration, my jade files for task1& task2 don't load. However, if they are both under /server/views/, they work.

Thanks.

**Comment by sonisaurabh19** [comment]
Any help guys...

**Comment by Marsup** [comment]
Hijacking an issue is not the best way to get help, especially in the wrong project.
Check your paths they seem wrong.
