### ISSUE TITLE
Support Promises in reply() interface

### ISSUE THREAD

**Issue by yonjah** [hapijs/hapi#2097]
As with every node app logic relays heavily on async calls.
Today you can only use pure callbacks with Hapi which can make you end up with messy code.
Promises would be a much nicer way for handling async calls, so instead of doing this -

``` javascript
server.pack.register({
        plugin: plugin,
    }, function callbackA(){
        doSomeMoreAsyncStuff(function callbackB() {
            //callbackB code
        });
});
```

We could do some thing like this -

``` javascript
server.pack.register({
    plugin: plugin,
}).then(function callbackA(){
    return doSomeMoreAsyncStuff();
}).then(function callbackB() {
    //callbackB code
});
```

In most cases code can be changed so it will still support both regular Callbacks and Promises style.

**Comment by SimonDegraeve** [comment]
@hueniverse 
> Nope. Sorry. You can wrap hapi yourself but I am not going to change the framework from callback to promises. And while I am not dismissing those who find promises to be better, the above example does not demonstrate any benefit.

I have on use case. I have an array of plugins like this
```
var plugins = [
    Auth,       
    {
        register: Database,
        options: {}
    },    
    Routes,      
    ...
]
```

So I would like to register all of them, in my main plugin like this
```
server.register(plugins, function (err) {
    if (err) {
        console.error('Failed to load a plugin:', err);
    }
});
```

But I want to set a `route prefix` for the `Routes` plugin and because this option is only available in the register function and not the plugin options, I end up doing something like this
```
var plugins = [
    [Auth],        
    [{
        register: Database,
        options: {}
    }],   
    [Routes, {
      routes: { prefix: '/v11 }
    }],     
    ...
]

plugins.forEach(function(plugin) {
    server.register(plugin[0], plugin[1], function (err) {
        if (err) {
            console.error('Failed to load a plugin:', err);
        }
    });
});
```
But then I have to use an external dependency like [async](https://github.com/caolan/async) to make it works serially (some plugins depends on each other).
If the register function is `Promise-able` it would e easier to control the flow, without dependencies. 

Actually I use ES6 with the [6to5](https://github.com/6to5/6to5) transpiler. It looks like this
```
export async function register(server, options, next) {
    ...

    // async / await is ES7 wrapper for generator/promise

    try {

    // UGLY: Transform callback to promise
    var registerFn = server.register;
    server.register = (...args) =>
      new Promise((resolve, reject) =>
        registerFn.apply(server, [...args, error => error ? reject(error) : resolve()])
      )

    // Register plugins
    for (let [plugin, options = {}] of plugins)) {
      await server.register(plugin, options);
    }

    return next();
  }
  catch (error) {

    return next(error);
  }
}
```

For this special use-case, being able to define `route prefix` directly in the plugin option would solve the problem. But I believe having the register function `promise-able` (and keep the callback, so people have the choice) is inevitable at some point with ES6 getting more and more used.

**Comment by hueniverse** [comment]
@SimonDegraeve this belongs in modules like glue where you can experiment with new interfaces for loading plugins.

**Comment by SimonDegraeve** [comment]
I am using glue to define my connections, and my main plugin. The reason I dont register the others plugin in the manifest is because I want to some encapsulation (like modules works). When I require the main module, I dont have to know that the Main plugin requires a Router plugin that requires a Route plugin that requires something else.... Or am I wrong about the good practise?

**Comment by bendrucker** [comment]
Just promisify the method you need

https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification

**Comment by mmc41** [comment]
@hueniverse If I understand your earlier comment in this thread correctly, promise failuires are not handled ? If so, it could be a big problem in future node versions. I just tried an example and I got the following warning in node 7.0.0 

(node:2725) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hueniverse** [comment]
@mmc41 not following how this is a problem hapi needs to handle. hapi doesn't use promises. If you add promises to your code, you should do it properly including handling rejections. I assume that if node core starts using promises, they will catch all their own rejections.

**Comment by kanongil** [comment]
Hapi already catches a `throw` from the handler, which returns an internal error response. Conceptually, a failed promise is an async `throw`, and it would make sense that hapi handles this in a similar way where it also returns an internal error response.
