### ISSUE TITLE
Abort response on stream error mid-response

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2121]
If a 200 response using a stream fails, the client will get an incomplete 200 response instead of a complete 500.

**Comment by feugy** [comment]
Hi !

Just in case, is this behaviour still complex to fix ?
I'm proxying data from S3 using streams, and would like to return a 404 when downloaded file doesn't exists, or a 500 when download failed for any other reason.

It's easy to mitigate the first, by testing the file existence, but I don't see any possibility to do the second.

Thanks in advance for your time !

**Comment by hueniverse** [comment]
No easy solution. Once you start piping the stream, you already set the status code.

**Comment by Marsup** [comment]
Facing the same issue, it seems adding `request.raw.res.destroy()` after https://github.com/hapijs/hapi/blob/513cea8a64a88cff3ca57cb0f23e8a843fb0259f/lib/transmit.js#L268 is sufficient to at least let the browser know something went wrong (aka forcefully interrupting the connection). See any downside to this ?

**Comment by kanongil** [comment]
Forcefully closing the socket is the only, and best, option there is. This is probably something that hapi should do already. Otherwise, the client will just wait for data that is never coming. Worse, if it is a http keep-alive request, it can have pending pipelined requests that will never be fulfilled.

The client should be able to deduce that it received a partial response, and handle it however it sees fit.
