### ISSUE TITLE
Confused about "reply()" vs "return reply()"

### ISSUE THREAD

**Issue by paulovieira** [hapijs/hapi#2168]
In the route handler, should I call 
`reply("some payload")` 
or 
`return reply("some payload")`? 

I see both versions in the documentation.

Suppose I don't want to use the response object returned by `reply`. Is there any difference then?

In the first case the handler will return undefined back to the router. In the second,  it will return the response. Is the response used for anything?

Thanks.

**Comment by isaldarriaga** [comment]
Just to complement the information (suggested read):

Use A Return Statement When Invoking Callbacks, Especially In A Guard Statement
By Ben Nadel on February 1, 2012

http://www.bennadel.com/blog/2323-use-a-return-statement-when-invoking-callbacks-especially-in-a-guard-statement.htm

**Comment by clivend** [comment]
+1 do we have a best practice in the end?

**Comment by johnbrett** [comment]
@clivend  as @hueniverse mentioned `return callback()` is always considered best practice.

**Comment by clivend** [comment]
sorry I didn't notice this is a "question" so maybe there's no "closed" event :)

**Comment by kswope** [comment]
As somebody with 20+ years of development and 3+ days of hapi I just have to say this is a horrible 'best practice'.  I think @csrl style, although messy, is so much more clear.  As somebody learning hapi I had to find this obscure github issue to figure out whats going on.  I'm still not sure because I wouldn't be surprised if someday (maybe even today) returning a promise from a handler does something.

In an untyped language seeing something like this below tells most programmers that returning the return value from B is important.  There is NO WAY anybody would think this means "run B and then return".  This means "return the return value of B".  
```
function A(){
  return B()
}
```

This is the kind of stuff that is making typescript and flow so popular now.

**Comment by tikotus** [comment]
Totally agree with @kswope, here for the same reason.

Also, what if the handler does a db query and does the reply asynchronously? Wasn't sure if that's allowed because of return in all examples.

**Comment by Humoyun** [comment]
So if I understood correctly, reply just returns response object and that response is not sent to the client (if the return is not used) until later in the request lifecycle?

**Comment by mtharrison** [comment]
> and that response is not sent to the client (if the return is not used) until later in the request lifecycle?

`return` or not has no bearing on lifecycle behaviour. Either way the response isn't sent until later.

**Comment by hueniverse** [comment]
In v16. None of this is relevant to v17.
