### ISSUE TITLE
About server.expose()

### ISSUE THREAD

**Issue by gagle** [hapijs/hapi#2341]
I simply want to now the reason or decision-making about having a `server.expose()` function. It is used to expose properties to the `server.plugins` namespace, but I have the feeling that it is a bit useless, it's just a more readable way to expose settings.

A plugin may fail to register, so we need to call `next(err)`, but then if it fails, we don't want to expose anything. Sure, all the subsequent plugins won't execute and `server.register()` will finish with an error but for me it's more cleaner if we expose the settings by calling `next(null, settings)`. This way we finish with an error or exposing settings, not both.

Current:
```js
module.exports.register = function (server, options, next) {
  server.expose('foo', 'bar');
  next();
};
```
What I'm taking about:
```js
module.exports.register = function (server, options, next) {
  next(null, {
    foo: 'bar'
  });
};
```

A benefit of having `server.expose()` is to be able to expose settings as soon as you can expose them, for example:

```js
module.exports.register = function (server, options, next) {
  foo(function (err, fooData) {
    if (err) return next(err);
    server.expose('foo', fooData);

    bar(function (err, barData) {
      if (err) return next(err);
      server.expose('bar', barData);
      next();
    });
  });
};

// Instead of:
module.exports.register = function (server, options, next) {
  var data = {};
  foo(function (err, fooData) {
    if (err) return next(err);
    data.foo = fooData;
    bar(function (err, barData) {
      if (err) return next(err);
      data.bar = barData;
      next(null, data);
    });
  });
};
```

**Comment by hueniverse** [comment]
While the idea is interesting, to link registration success with exposing a public api from the plugin, it is at best an incomplete solution. Since we cannot undo any of the other changes a plugin can make on the server (routes, state, cache, etc.), applying this to just expose isn't very useful or consistent.

You can simply defer calling `expose()` until you know everything else worked out right.

As for the reason for `expose()`, it is a simple utility to help you better manage what the plugin is exposing in the shared namespace. You can access that namespace directly if you want.
