### ISSUE TITLE
Post-requisites?

### ISSUE THREAD

**Issue by paulovieira** [hapijs/hapi#2351]
Adding pre-requisites to the route `config` is a great way to reuse little bits of common logic among different routes.

In the same vein, would it make sense to introduce route *post-requisites* (for lack of a better word)? I searched the closed issues about this idea but couldn't find anything.

This would be a natural place to do stuff like:
 - close database connections
 - apply Hoek.transform to format the object / array of objects of the response (delete some properties, move properties from nested objectes to the top object, etc)

Essentially, post-requisites would be the place where common post-processing utilities would be used. 

`onPostHandler` is not a good place for this because we don't want to execute those post-processing utilities for all routes (only for some)

Looking at the [request lifecycle](http://hapijs.com/api#request-lifecycle), we have:

 - ...
 - `onPreHandler` extension point
 - Route prerequisites
 - Route handler
 - `onPostHandler` extension point
 - ...

Adding post-requisites between the Route handler and `onPostHandler` extension point would make the lifecycle sequence more symmetrical around the handler.

**Comment by gergoerdosi** [comment]
See the discussion here: https://github.com/hapijs/contrib/issues/13

**Comment by hueniverse** [comment]
I still don't like this idea.

It is also not really as symmetric as you claim because in many response types (views, file), the processing isn't really done until after `onPreResponse` which means these post handler methods will not really be able to do much cleanup.

You already have other extension hooks as well as the ability to set tails and use the request events emitted when things are done and ready to be cleaned up.

I will need to see some specific examples of how much the code is cleaner and easier to maintain with this feature compared to the current setup.
