### ISSUE TITLE
setting undefined headers on transmit

### ISSUE THREAD

**Issue by stephen-bartell** [hapijs/hapi#2352]
I'm not sure of what the policy is re bugs due to fixes in iojs which aren't released yet in node (which may or may not be released soon).  

heres one.  the transmit module allows undefined headers to be set here https://github.com/hapijs/hapi/blob/master/lib/transmit.js#L250.

related issue for context https://github.com/iojs/io.js/issues/450

**Comment by hueniverse** [comment]
First, hapi is only targeting the Joyent distribution of node. This is largely logistical until it is easy to setup travis to test with both distributions.

Second, I am not following what's the issue here. The framework doesn't care what you put in headers so just stop setting undefined. What am I missing?

**Comment by AdriVanHoudt** [comment]
@hueniverse you can test io.js in travis see http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#iojs_support
And an example on how to test both http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by hueniverse** [comment]
@AdriVanHoudt already done.

**Comment by AdriVanHoudt** [comment]
@hueniverse cool! Didn't notice when the last post was posted sorry.

**Comment by rainabba** [comment]
@hueniverse I just landed here because (as I've seen a few times now), a plugin is setting a header with value of undefined and the resulting error has no reference to the plugin which makes it VERY hard to debug. Any suggestions on how to best do that? In my case, I was working with a plugin that modified headers so it wasn't hard to figure out which and then search for ".header", but if I'd been changing something at another level, I would have had no idea where to even begin looking.

**Comment by hueniverse** [comment]
We'll need to address it as part of node.js 4.0 release testing.
