### ISSUE TITLE
Handler caching with proxy option?

### ISSUE THREAD

**Issue by NataliaLKB** [hapijs/hapi#2377]
For our app we are using Hapi to create a proxy. You are welcome to view it [here](https://github.com/foundersandcoders/camdenmaps/tree/dev/server).

MapUri and onResponse work wonderfully and are perfect for our application. The next logical step is to add server-side caching. Though the documentation is quite good for standard handlers, I cannot see an example of caching in hapi with a proxy in the handler. 

Is this a possibility, or will it be made a possibility in the near future? 

Thank you in advance for your time.

**Comment by kanongil** [comment]
Try to take a look at #2315 for the current options. If you need more feedback I suggest you make an new issue at [hapijs/discuss](https://github.com/hapijs/discuss).

**Comment by NataliaLKB** [comment]
@kanongil thanks for your reply.

I have seen that issue, and the answer and it was one of the first things we tried in our project. Unfortunately, it still doesn't work effectively with the proxy setup with is recommended on the hapi documentation. We ended up not using hapi caching and completed the task using node-cache. 

I am a huge fan of hapi, so I found it odd that such a simple task was make so hard and we ended up reaching outside of hapi to solve it.

Anyway I do appreciate your reply and using the module node-cache it was a trivial problem to solve

**Comment by hueniverse** [comment]
Server side caching of HTTP responses is actually very complicated. It is outside the scope of hapi to provide an HTTP cache. I would not call it a "simple task", not is it "so hard" to write a handler that performs this. You could also use a server method with cache that takes a string URI and string method input and returns the payload and call that in your handler.

Keep in mind that caching will make non-cached requests much slower because you will need to read the entire payload into memory vs just piping the stream.
