### ISSUE TITLE
Response is not wrapped in jsonp if reply.file is used

### ISSUE THREAD

**Issue by zedd45** [hapijs/hapi#2486]
I'm using Hapi `v0.7.5` (because we need to migrate from `hapi.pack` to `hapi glue`) with node `v0.12.0` (which i need to downgrade to `v0.10.0`, but [that's another story](http://hueniverse.com/2015/03/02/the-node-version-dilemma/)).

This is possibly related to #2466, but I didn't see it listed as one of the conditions. 

When I return a file's contents as the response body, it doesn't become wrapped in the callback, even if jsonp is enabled. 

Original code snippet:
```
 config: {
      handler: {
        file: __dirname + 'myfile.json'
      },
      // ...
      jsonp: 'callback',
    }
```

Test scenario code:
```
var handler = function ( request, reply ) {
    console.log('request', request);
    if (true) {
      return reply({ 'test': true});
    } else {
      return reply.file( __dirname + 'myfile.json');
    }
  };
```

The top condition will return a JSONP response, but if you invert the logic (aka `false`) it will send back the contents of the file, but not wrapped in a callback.

**Comment by hueniverse** [comment]
While this is correct, the documentation clearly states that the JSONP feature does not work with stream responses which include files. If you want to combine JSONP with files, you need to serialize the file content manually and pass it to `reply()` as a string or buffer.

I would be open to reconsider this as a new feature request if more people indicated they needed it. It's a bit messy to do because it needs to replace the file stream with a stream that can combine strings and streams in a unified interface.

**Comment by zedd45** [comment]
Thanks @hueniverse. I was able to work out a solution by reading the relatively small file async with `fs.readFile`which serialized it as you have stated. 

```
fs.readFile(filePath, 'utf8', function(err, data) {
        if (err) {
          Boom.badImplementation("..");
        } else {
          return reply(data);
        }
```

This serialized it in the way I expected (with the `jsonp` wrapper around it). 

Thanks for your time!
