### ISSUE TITLE
Plugin auth strategy

### ISSUE THREAD

**Issue by seemsindie** [hapijs/hapi#2518]
I have hapi-pg plugin registered before everything else, and before i load my routes i am creating auth strategy. hapi-pg plugin attaches pg.client to every request. My question is how do i use it in auth strategy, because 'this' doesn't contain the pg.client?

**Comment by hulbert** [comment]
@seemsindie looks like you can write your own auth scheme since it has access to request/reply, and then could pass request into your validateFunc (https://github.com/hapijs/hapi-auth-basic/blob/master/lib/index.js#L32). That said, I would just use a connection pool and store something that gets connections on `server`

**Comment by hueniverse** [comment]
@seemsindie I could use a bit more context here. What are you trying to do, which auth scheme are you using, etc.
