### ISSUE TITLE
Using route prerequisites for checking user roles

### ISSUE THREAD

**Issue by 2color** [hapijs/hapi#2541]
Say I have different user roles and I want to give only a specific role access to a route, is it good practice to check the user type in the session cookie inside a prerequisite function?

**Comment by AdriVanHoudt** [comment]
I would check with the db, the cookie can be modified so a user could potentially grant himself other roles that way

**Comment by AdriVanHoudt** [comment]
The use of prerequisites is the way to go though

**Comment by 2color** [comment]
>I would check with the db, the cookie can be modified so a user could potentially grant himself other roles that way 
The example was assuming an encrypted http only session cookie.

I'll try it out with prerequisites and see how it goes.

**Comment by 2color** [comment]
Thanks @AdriVanHoudt :+1:

**Comment by poeticninja** [comment]
If you are using [hapi-auth-cookie] (https://github.com/hapijs/hapi-auth-cookie) then you can use the session cookie for permissions. A user wouldn't be able to modify that because the session cookie is encrypted with [iron](https://github.com/hueniverse/iron) and any modification would invalidate the session. You can get access to the session data in your pre handler with `request.auth.credentials`. By doing this you know it's secure and you don't have to hit your database every time.

But there are always multiple ways to solve a problem. :smile:

**Comment by AdriVanHoudt** [comment]
Didn't know that, in that case it's safe :D

**Comment by poeticninja** [comment]
And if you decide to protect a route based on a user role you can use scopes if they are set in the session object. 

```
var user = {
    id: 123,
    scope: 'admin'
};
request.auth.session.set(user)
```

Now any route that has the auth the object set with a scope of admin has protection and only an admin could access it. Example route,

```
server.route({
  method: 'GET',
  path: '/admin-panel',
  config: {
    auth: {
      strategy: 'strategy-name',
      scope: ['admin']
    },
    handler: function (request, reply) {

      return reply({message: 'Success, you can access a route that requires the admin role!'});

    }
  }
});
```

Hapi is pretty freaking awesome when it comes to auth.

**Comment by 2color** [comment]
> Now any route that has the auth the object set with a scope of admin has protection and only an admin could access it. Example route,

That's great! Much nicer than prerequisites. 

> Hapi is pretty freaking awesome when it comes to auth.

Indeed

**Comment by Marsup** [comment]
Discussions like that would be better in the [discuss](https://github.com/hapijs/discuss/) repo in the future.
