### ISSUE TITLE
Question about error handling when calling server.start

### ISSUE THREAD

**Issue by FennNaten** [hapijs/hapi#2565]
Hi,
I had to look at Server.prototype.start recently and there is something that left me wondering: even if the method takes a callback with a `function(err)` signature, the synchronous part of the method (checking if connections exist, checking if all dependencies are registered) throws instead of using this callback. So, the method has two ways of failing, synchronous throw requiring a try/catch for custom handling or asynchronous error bubbling up.
My question is: considering that the errors causing a throw are asserted, so, expected, why having chosen to throw instead of returning them as error in the callback?
I'm not saying one option would be better than the other, I just would like to understand the choice, if someone has some spare time for that ;) 

Thanks in advance!

**Comment by devinivy** [comment]
I believe that the asserted errors are fatal, indicating that something went very wrong.  In this situation the app should crash, and some code should be rewritten to satisfy the failed assertion.  You'll find assertions like these all over the codebase: https://github.com/hapijs/hapi/search?utf8=%E2%9C%93&q=Hoek.assert&type=Code

**Comment by hueniverse** [comment]
In practice, errors in start() should blow the server up as it is in an unstable state. Basically, if you get an error, you can't really recover as you can't really tell what state the different connections are in, what state the plugins are in (they cannot be registered again, but after() calls will happen again), and what is going on with the cache.

I am going to change `start()` to always throw if there is an error no matter where it comes from. `stop()` on the other hand, is trickier to figure out but calling stop multiple times should be safe.

**Comment by FennNaten** [comment]
Thanks for the answer, makes more sense IMHO to have a consistent behavior.

**Comment by hueniverse** [comment]
Well, it is **mostly** consistent. If you call `start()` the first time, things should blow up because you are in unknown state. If you then add another connection and call `start()` again, you don't want it to throw, but to return a callback with the error because you now have a running server serving requests. So it's tricky.

I am still undecided about whether I should go back to callback errors (and never throw), but I'm not sure. I'll sleep on it and decide tomorrow.

**Comment by hueniverse** [comment]
The rule is, throw on errors that must be fixed at development time - errors that are impossible to recover from at run time (e.g. missing callback, invalid function arguments), and return a callback error on other errors that are more likely runtime errors where there might be a way to recover or at least properly shut down the server (take logs, cores, etc.).

`start()` is tricky as I mentioned before because it if fails, you are probably in bad state and should just shut down the process. It's hard to draw a hard line between errors that should be thrown and those that should be returned via a callback and you can't really use a clear rule. For example, invalid callback or function arguments are pointless to return via a callback. But what about an invalid plugin? That's clearly not a run time error and you should never do anything but blow up in that case.

Also, once you enter a new tick catching errors becomes annoying and you need to wrap your `start()` call with a domain which is never a good idea.

After a night sleep I've decided to largely keep things they way they are but am going to document this better so that people will properly handle `start()` errors.
