### ISSUE TITLE
Update hapijs/shot to 1.5.1 from 1.5.0

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2586]

**Comment by hueniverse** [comment]
@iamdoron @Marsup the changes in shot 1.5.1 break a bunch of the transmit tests. Before I dig deeper into this, is the problem with the hapi tests or the changes in shot?

**Comment by iamdoron** [comment]
The first one I checked, shot now stores the buffer in `payloadBuffer`. That should solve it:
```javascript
it('returns an JSONP response with compression', function (done) {

            var handler = function (request, reply) {

                var parts = request.params.name.split('/');
                return reply({ first: parts[0], last: parts[1] });
            };

            var server = new Hapi.Server();
            server.connection();
            server.route({
                method: 'GET',
                path: '/user/{name*2}',
                config: {
                    handler: handler,
                    jsonp: 'callback'
                }
            });

            server.inject({ url: '/user/1/2?callback=docall', headers: { 'accept-encoding': 'gzip' } }, function (res) {

                expect(res.headers['content-type']).to.equal('text/javascript; charset=utf-8');
                expect(res.headers['content-encoding']).to.equal('gzip');
                expect(res.headers.vary).to.equal('accept-encoding');
                Zlib.unzip(res.payloadBuffer, function (err, result) {
                    console.log(err);
                    expect(err).to.not.exist();
                    expect(result.toString()).to.equal('/**/docall({"first":"1","last":"2"});');
                    done();
                });
            });
        });
```

**Comment by iamdoron** [comment]
oh, I think I'm wrong - maybe there is an issue with the first one. I'll further look into it.

**Comment by iamdoron** [comment]
ok

So- the question is what is `res.payload` - is it a buffer? is it string in utf8? binary?
The thing is, when it was a 'binary' string, there was no problem with regular english strings and real binary strings (from a binary file, for instance), as they were in an equal encoding. 

```javascript
new Buffer("doron", 'utf8').toString('binary') === "doron"
new Buffer("\x89PNG\r", 'binary').toString('utf8') !== "\x89PNG\r"
```

After the change I introduced in shot, now `res.payload` is utf8, `res.payloadBuffer` is `Buffer`. I suggest to change `res.payload` to buffer, and let either hapi or the user decide what to do with it, since the buffer is what really being transmitted - maybe hapi tries to parse it to JSON or leave it be.

**Comment by iamdoron** [comment]
There was a problem with the names - https://github.com/hapijs/shot/pull/32

according to hapi api docs:

>
- `payload` - the response payload string.
- `rawPayload` - the raw response payload buffer.
