### ISSUE TITLE
server/connection-wide Joi defaults

### ISSUE THREAD

**Issue by hulbert** [hapijs/hapi#2617]
Sorry to create an issue but can't figure out the appropriate way (if any) to do this. I'd like to tell Joi not to convert types (that is, set Joi's option of `convert: false`) when validating payloads. (It's frankly surprising to me that this is enabled for JSON payloads.)

I'm looking for a way to change the default for all `server.route` definitions.

**Comment by hulbert** [comment]
To add onto this, looks like you can set default Joi options for connections like so in the example, but it's unclear if there is a way to only do this to the payload. The need being that I want string to number conversion for query parameters but not POST'ed JSON documents.

```js
let serverOptions = {
    connections: {
        validate: {
            options: {
                convert: false
            }
        }
    }
}

let server = new Hapi.Server(serverOptions)
```

**Comment by hueniverse** [comment]
There is no way to set global options for some of the validation rules. But you can set it for an individual joi schema. See https://github.com/hapijs/joi#anyoptionsoptions.

```js
var schema = Joi.object({ key: Joi.number() }).options({ convert: false });
```

**Comment by hulbert** [comment]
@hueniverse thanks for taking the time. It seems that by setting it on a per schema basis that I would need to set it for all schemas used for payload validation? I am concerned a developer less well-versed in Hapi would miss that. Here's my case for why I think some change is needed:

- Converting types of a JSON payload violates the principal of least astonishment. Similarly, not converting types for query parameters would violate the principle of least astonishment as well (i.e. one expects `String('3')` to become `Number(3)` when looking at the `request.query` map. 

    I've been building a medium-sized API on Hapi for 3 months and just yesterday learned that strings in my POST'ed JSON documents may be converted to numbers. That is, I'm not actually getting the output of JSON.parse(<raw request payload>), I'm getting some slightly modified version of that which happens to be an implementation details of an underlying library. 
   
   I learned this via a test I wrote.

- With this surprising experience, I would hope at least to have the ability to override the default behavior. I would make the case that the default behavior is wrong for the `payload` but understand that changing that in a release would probably break some apps. 

    A reasonable way to do that would be like above in the server options but able to set the default options for specific validation types,  i.e. `connections.routes.validate.payload.options.convert = true`

**Comment by hueniverse** [comment]
I disagree with what's the proper way to validate a payload. The goal of the schema is to ensure the data passing through to the handler is guaranteed to comply with expectations. If a value needs to a be a number, it should be an actual number, not a string. If anything, your approach makes your code more complex and misses the point of the conversion feature in joi. The fact that this is the first time this issue has come up in over 4 years shows that most people are using this feature as intended.

That said, it is your decision how you would like to process incoming payload data to your handlers. What you can do is simply assign the modified option object and use that as the root of your payload validations: `var payload = Joi.options({ convert: false });` then in route config simply use that instead of joi: `payload.number()`. There really is no meaningful difference between this style and your request.

I am not inclined to add more configuration options for something that will make the config unnecessarily verbose. If this was requested by a significant number of people I would be willing to reconsider but I really think your expectations are the exception here.

**Comment by hueniverse** [comment]
Also, you can get the unmodified payload under `request.orig.payload`.

**Comment by hulbert** [comment]
> The goal of the schema is to ensure the data passing through to the handler is guaranteed to comply with expectations. If a value needs to a be a number, it should be an actual number, not a string.

I see the validation schemas as having two purposes: 

1. Guarantee the handler receives data in the appropriate format, which seems to be the case you're talking about here

2. Force clients of an API to interact with the API appropriately. To change context of what you said above—"If a value needs to a be a number, it should be an actual number, not a string."—I would expect an API client to give the API a number not a string. Guess it depends on the perspective with which you are using your validation schemas.

>  If this was requested by a significant number of people I would be willing to reconsider but I really think your expectations are the exception here.

I wonder how many users are actually aware of this behavior. The default behavior, when using the validation schemas in light of purpose 2 above, is hard to discover. You'd have to intentionally send a JSON payload with the incorrect type (why I used the term surprising). 

I understand not wanting to make this change (and appreciate your suggestion of working around it; it is pretty elegant) but wonder if # of requests for this is the appropriate measure since it is not easily discovered without edge-case testing or careful reading of the docs.

**Comment by hueniverse** [comment]
I'll take a PR making the docs clearer on this point.
