### ISSUE TITLE
Resource that is been validated deleted from the validation context

### ISSUE THREAD

**Issue by xilix** [hapijs/hapi#2678]
I'm currently in an use case where i need to apply conditional validations according some variables in a complex payload, that are not always in the payload leaf that is been validated.

I've seen here https://github.com/hapijs/hapi/blob/master/lib/validation.js#L124 that the resource that is been validated is deleted from the validation context. Seems that this deletion was introduced on #1643. Is there are any reason to delete the resource that is been validated from the validation context?

As now is impossible to access to the payload in the validation context when validating the payload i'm considering to duplicate this variables and send them with the http headers or with the url params as in https://github.com/hapijs/hapi/blob/master/lib/validation.js#L111 is seting up them in the validation context. My question is if this is a deprecated way to perform complex conditional validations according hapi roadmap or if ti's a safe approach.

**Comment by hueniverse** [comment]
It is removed because you don't want the data being validated to also be in the context. First, there is no point to that since you get the same object as the first argument of the validation function. Second, validation also means changing the data (type casting, etc.) which will not be reflected in the context version which is going to cause unexpected bugs.
