### ISSUE TITLE
Missing property server.views

### ISSUE THREAD

**Issue by vitaliyAtSvarog** [hapijs/hapi#2713]
```javascript
var Hapi = require('hapi');
var server = new Hapi.Server();

server.connection({
    port: cfg.port,
    host: cfg.host,
    routes: {
        cors: true
    }
});

server.views({
	engines: {
		'slm': require('slm')
	},
	basePath: __dirname + '/backend/views',
	compileOptions: {
		basePath: __dirname + '/backend/views',
        useCache: cfg.useCache // disable internal cache - useful for development
    },
    isCached: cfg.useCache // disable hapi view cache
});
```
then in console write 'node server.js' and get error http://screencast.com/t/TfZQLTbb

see debug

![error](https://cloud.githubusercontent.com/assets/13368159/9288028/3920db02-435d-11e5-9862-784d2f44d285.png)

**Comment by gergoerdosi** [comment]
You need register the `vision` plugin if you use hapi 9.x.x. 

```js
server.register(require('vision'), function (err) {
    if (err) {
        throw err;
    }

    server.views({ ... });

    server.start(function () {
        server.log('info', 'Server running at: ' + server.info.uri);
    });
});

**Comment by vitaliyAtSvarog** [comment]
Is that described somewhere in the documentation?
![docs](https://cloud.githubusercontent.com/assets/13368159/9288085/60b6109a-435f-11e5-86b5-c98e3844a484.png)

**Comment by gergoerdosi** [comment]
Not yet, the documentation needs an update.

**Comment by vitaliyAtSvarog** [comment]
gergoerdosi thx. You helps me :+1:

**Comment by AdriVanHoudt** [comment]
@vitaliyAtSvarog read https://github.com/hapijs/hapi/issues/2682

**Comment by dlong500** [comment]
Yeah, the documentation and plugins page really need updating.  Even though I specifically read about the breaking changes in the v9.0.0 release notes it still took me a while to figure out what to actually DO to migrate the code.  In addition to registering the newly separated plugins, you also have to actually install them via npm (and even then it is somewhat obscure, because the plugin names aren't prefixed with hapi--instead it's just vision and inert).  They aren't even listed on the "Plugins" page at the site yet either.

With as rapid as updates are for hapi, wouldn't it be better to have some type of versioned documentation like MySQL?  I know that a lot of the coders have more important things to do than update documentation, but it's definitely important.  I'd volunteer myself but I'm not an expert at even just using hapi yet...

**Comment by hueniverse** [comment]
This is the first breaking release since last December. I wouldn't call it rapid.

**Comment by dlong500** [comment]
Sorry, I didn't mean to imply there are breaking changes all the time.  But I'd still call going from version 2.x to 9.x in the past year and a half a fairly rapid pace.  Even if changes aren't breaking it could still be somewhat difficult to stay on top of things without really good documentation.

That being said I'd much rather have the type of stellar development that has been going on than to have awesome documentation with a stagnant framework.  So thanks for your work.
