### ISSUE TITLE
Support connectionless plugins

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2811]
Adds a new plugin attribute `connections` which when set to `false` removes the `server.connection` array and prevents the plugin from performing operations on the connections. This means the plugin operates exclusively on the server and is available to connections added after the plugin was already registered.

**Comment by devinivy** [comment]
So what exactly would happen if I make a connectionless plugin that calls `server.route()` then register it to a non-empty selection?  It seems like it would silently not do anything.  Is there a reason to allow connectionless plugins to be registered to a non-empty selection?

Also might be nice to enumerate or mark the server methods (in documentation) that do not act on a connection so that it's clear what's kosher.

**Comment by hueniverse** [comment]
It will throw. The server object you get will have no connections array.
