### ISSUE TITLE
How to properly close external connections in a plugin?

### ISSUE THREAD

**Issue by dominicumbeer** [hapijs/hapi#2839]
Recently I was wondering how to properly close my database connection in a plugin. At register time I open a connection to a Mysql database within the plugin.

During testing I realised that the process is still running due to the open connection and I would like to properly close the connection after the tests have been executed.

My test code looks similar to that (removed unimportant code):

```javascript
it('should close connection after execution', function(done) {
  var server = new Hapi.Server();
  server.connection({port: 8080});

  var plugin = require(‘./myPlugin’);

  server.register(plugin, function(err) {
     
       // Do some testing

       // Tear down plugin and close connection?

       return done()
  });
});
```

Maybe important to say is that I don’t start the server in the test.

Is there any possibility to detach/deregister a plugin and execute code based on that event? What is best practise?

Thanks for the support

**Comment by devinivy** [comment]
There's no way to detach or unregister a plugin.  Typically I would do init and teardown during `onPreStart` (`server.after()`) and `onPostStop` extensions respectively.  You can initialize your server without starting it using `server.initialize()`– that will call the `onPreStart` (`server.after()`) extensions.  You can then still use `server.stop()` to trigger the `onPostStop` extensions.

**Comment by dominicumbeer** [comment]
Sounds reasonable. Didn’t know that it is possible to initialise the server without starting it. 

Having a tear down function or something similar would make the process clearer in my opinion.

**Comment by devinivy** [comment]
That's more or less the intention of the server lifecycle extensions– the lifecycle of the plugin is tied to the state of the server, probably because unregistering a plugin independently of initializing/stopping the server would lead to confusion (request lifecycle extensions would get reshuffled, routes could disappear, etc.).

Hope this solution works out nicely for you!  If you find the code in your tests to be too bulky, initializing and stopping the server, maybe you could write a small tool to automate the process.
