### ISSUE TITLE
Allow empty response to default to 204

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#2845]

**Comment by kanongil** [comment]
What changed since #1470?

**Comment by hueniverse** [comment]
I'm seeing cases where a 200 with no payload is getting browsers stuck or error out. I found myself sending useless responses just to avoid these errors so it looks like browsers now prefer a 204 over 200 (or even expect it).

**Comment by kanongil** [comment]
Are you sure it is not due to a missing `content-type` header for those responses?

200 responses has a payload by definition, and I'd guess that browsers could get confused about this.

I'd probably change the semantics of the reply argument, so that `reply()` signals the no payload case (using code 204), while `reply('')` signals that there is a zero-length payload, adding the default content-type for string response.

**Comment by hueniverse** [comment]
That's a good idea.

**Comment by gergoerdosi** [comment]
Why 200 is the default? Just to not introduce a breaking change?

**Comment by hueniverse** [comment]
Because too many clients hard code 200 as success.
