### ISSUE TITLE
Can't cache responses because of the chunked encoding response

### ISSUE THREAD

**Issue by tiagoalves** [hapijs/hapi#2978]
As requested by @hueniverse, I'm moving https://github.com/hapijs/hapi-auth-hawk/issues/24 here:

We're trying to cache responses of hawk-enabled endpoints (with hapijs/hapi-auth-hawk) with Varnish without success. The Varnish team told us that our response is invalid.

Take this example request and response made with `telnet`:

```
GET /some/endpoint HTTP/1.1
User-Agent: curl/7.15.5 (i386-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Host: some-host.com
Authorization: Hawk id="some_id", ts="1450174655", nonce="fhy_aa", mac="/CuTVabcD+x4Fl1asdf546agadfgaN/MvDnrLBpkkadagsdg="
Accept: ​*/*​

HTTP/1.1 200 OK
media-type: application/json;v=1
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 698
trailer: server-authorization
transfer-encoding: chunked
accept-ranges: bytes
Date: Tue, 15 Dec 2015 10:18:02 GMT
Connection: keep-alive

2ba
{"some":{"beautiful payload":"right here"}}
0
server-authorization: Hawk mac="DnKbLcQLAQOGG+234x75b1B8kDnu/TRnoE0faFK9va1=", hash="+GIUAwzO+F//FEeuyeRTj+123/6AgfhpkB5g8Xuxg3U="
```

There appear to be two problems.

The first is that requests with `transfer-encoding: chunked` must not have a `content-length` header. So, maybe we should `delete response.headers['content-length']`. But this isn't the actual reason why Varnish isn't caching our response.

The second problem is that the response body is, apparently, not actually chunked-encoded. I made a test where I removed that header (this line https://github.com/hapijs/hapi-auth-hawk/blob/master/lib/index.js#L86) and Varnish was able to cache the response.

Would it be safe to remove the `transfer-encoding: chunked` response header?

Also, would it make sense to make the whole server-authentication process optional?

Thanks!

**Comment by hueniverse** [comment]
The response uses chunked encoding because it uses the HTTP trailer headers (it's how the HTTP parser knows to parse the headers at the end of the payload separate from the actual payload. There should be no issue caching chunked messages. I don't know why Varnish is having a problem with it. If you notice in the example above, you are not actually allowing any caching (cache-control: no-cache).

As for the chunked encoding with content type, that might need a fix in node. I'll follow up on that one.
