### ISSUE TITLE
Server.inject sets payload to null

### ISSUE THREAD

**Issue by Bondza** [hapijs/hapi#3022]
Hey,

I am trying to use `Server.inject` to forward requests from one end point to others depending on data in the request. No matter what I assign payload option to `inject`, the next handler function receives the payload `null`. [Here](http://pastebin.com/yLnjdMW1) is a small example to reproduce this. I am running node 5.4.1 with Hapi 12.1.0.

I think the issue is that when the dispatch function [creates the request object](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L229), it simply [sets the payload](https://github.com/hapijs/hapi/blob/master/lib/request.js#L129) property to `null`.

Would changing [request.js#L129](https://github.com/hapijs/hapi/blob/master/lib/request.js#L129) to: `this.payload = options.payload || null;` fix this?

**Comment by vdeturckheim** [comment]
I believe this fails because you send a string payload payload [when the default type is a json](https://github.com/hapijs/hapi/blob/master/API.md#serverinjectoptions-callback).

**Comment by Bondza** [comment]
Sorry, I should have included that in the example I sent before. But I tried sending the `request.query` object as payload at first and that did not work either. [This example](http://pastebin.com/aMa6gwKy) yields the same result as the previous one.

**Comment by johnbrett** [comment]
They payload will always be null for a GET route. Does this happen for POST
routes as well?

**Comment by vdeturckheim** [comment]
Have you tried to send a payload to a POST/PUT route? I believe it is not standard to do so on a GET route...

**Comment by vdeturckheim** [comment]
:+1: @johnbrett

**Comment by devinivy** [comment]
Yeah, as I recall hapi wont bother parsing payloads on GET requests.  If you're sending parameters to a GET route, they should be part of the URI.

**Comment by hueniverse** [comment]
Blame HTTP.

**Comment by Bondza** [comment]
You are absolutely right, of course. It works for POST routes. My bad, thanks for the quick response.

**Comment by leobudima** [comment]
Sorry to bring this up again - I have the same problem. Since I'm in process of replacing the existing server and can't change client apps, could you recommend best way to use payload data in handler for a GET route anyway? Thanks!

**Comment by hueniverse** [comment]
An existing node server?

**Comment by leobudima** [comment]
Yeah, a Sails.js based app - the "get requests" are actually being sent through websockets which are then injected (server.inject) into regular Hapi processing via a plugin. The query params are being set in the client app as an object and forwarded in the plugin as payload, but it doesn't get through to injected request, since it's a GET. If you have any recommendation on how to work around it, at any point in the process, I'd be grateful :)

**Comment by hueniverse** [comment]
So it's not actually coming in as an HTTP get with payload?

**Comment by leobudima** [comment]
Well, I'm guessing that it being injected from the plugin as a GET request is the same, in terms of parsing payload, as if it came in that form originally? 

Thank you for your time to consider my questions!

**Comment by hueniverse** [comment]
I am not sure I understand the setup (and I don't really have the time to dig into it), but you should try and use onRequest ext to change the method to POST or something like that.

**Comment by leobudima** [comment]
If somebody else stumbles on a similar problem as OP and me:

- sending a GET request (or injecting it) with a payload will get you an empty request.payload in your handler and it can't be easily worked around - which is ok and expected - as @hueniverse said, it's how HTTP is meant to work, after all

- my solution was to simply convert payloads into query params in client-side library that sends the requests, so that my other client-side code doesn't change:


```
let urlParams = Object.keys(payload).map((key) => {
    return encodeURIComponent(key) + '=' + encodeURIComponent(payload[key]);
}).join('&');

if (urlParams.length) {
    url += '/?' + urlParams;
}
```

**Comment by Marsup** [comment]
It would be far more efficient to make that route a POST, since you're sending your data through websocket it doesn't really matter anyway.
