### ISSUE TITLE
how to use payload for auth check ?

### ISSUE THREAD

**Issue by willin** [hapijs/hapi#3098]
scheme: 

```js
scheme = {
    authenticate: (request, reply) => {
      return reply(null, {
        credentials: {
          user: {}
        }
      });
    },
    payload: (request, reply) => {
      return reply.continue({
        credentials: {
          user: { uid: 1 }
        }
      });
    },
    options: { payload: true }
  };
```

config:

```js
server.auth.strategy('standard', 'test',options);
server.auth.default({
    strategy: 'standard',
    scope: ['user'],
    payload: true
  });
```

route:

```js
{
  method: 'post',
  path: '/',
  config: {
    auth: {
      payload: true
    },
    validate: {
      payload: {
        auth: joi.string().length(32).required().description('Auth Token')
      },
      failAction: (req, reply) => {
        return reply(boom.unauthorized('Invalid Auth Token.'));
      }
    },
    handler: homeHandler
  }
}
```

Result always:

```js
{
    "credentials": {
        "user": {}
    }
}
```

why?

how to use payload for auth check ?

**Comment by AdriVanHoudt** [comment]
see https://github.com/hapijs/hapi/issues/3070

**Comment by willin** [comment]
@AdriVanHoudt  i tried #2232 demo:

```js
var hapi = require('hapi');
var server = new hapi.Server();
server.connection({
  host: '127.0.0.1',
  port: 4000
});
// server.js
server.auth.scheme("my_custom_scheme", function(server, options) {
  return {
    authenticate: function(request, reply) {

      // authentication doesn't anything, we just keep it
      // cause it's a required function?
      return reply(null, {
        credentials: {
          user: {}
        }
      });
    },
    payload: function(request, reply) {

      user = magic_code();

      // here we fetch the parsed payload ?
      payload = request.payload;

      if (error) {
        console.error(error);

        return reply({
          succes: false,
          error: {
            message: error,
            code: 'db_error'
          }
        });
      }

      if (user === null) {
        return reply({
          error: 'user_not_found',
          succes: false
        });
      }

      // inject use into credentials object ?
      request.auth.credentials.user = user;

      return reply();
    },
    options: {
      payload: true
    }
  };
});

server.auth.strategy('payload', 'my_custom_scheme');

server.route({
  method: 'POST',
  path: '/api/v1/settings',
  config: {
    auth: {
      strategies: ["payload"],
      payload: true
    },
    handler: function(req, res) {
      res(200);
    }
  }
});

server.start();
```


the same result:
```
{
    "credentials": {
        "user": {}
    }
}
```

**Comment by AdriVanHoudt** [comment]
read https://github.com/hapijs/hapi/blob/master/API.md#serverauthschemename-scheme

**Comment by willin** [comment]
config.auth.payload

scheme.payload && scheme.options.payload  

all tried, not work

**Comment by willin** [comment]
@AdriVanHoudt  @hems

https://github.com/hapijs/hapi/issues/2232#issuecomment-65166499 

is this demo not compatible with the latest version 13.x any more?

can anyone give me a demo?

**Comment by AdriVanHoudt** [comment]
is there something not clear about the docs that you are unable to make this work?

**Comment by willin** [comment]
@AdriVanHoudt   i found where the problem is:

```
{
  method: 'post',
  path: '/',
  config: {
    // auth: {
    //   scope: ['user', 'admin']
    // },
    validate: {
      payload: {
        auth: joi.string().length(32).required().description('Auth Token')
      },
      failAction: (req, reply) => {
        return reply(boom.unauthorized('Invalid Auth Token.'));
      }
    },
    handler: checkUsernameHandler
  }
}
```

if I add the `scope` then the payload validation func not exec.

**Comment by AdriVanHoudt** [comment]
in that snippet you are validating the schema of the payload not using the payload to validate credentials.
what is it that you want to do exactly?

**Comment by willin** [comment]
api service, without cookie or session.

1. POST /login with username and password, then get a random string(auth token)
2. Save the auth token in redis with user info(like `scope`)
3. Pass the token as a payload param,  validate with redis data,

**Comment by AdriVanHoudt** [comment]
is there a reason for the token to be in the payload and not the Authorization header for example?

**Comment by willin** [comment]
e.g. app developers have no idea with 'HEADER'

**Comment by mtharrison** [comment]
?

**Comment by willin** [comment]
project requirements is so

**Comment by AdriVanHoudt** [comment]
it is a weird way to do authorization...

**Comment by willin** [comment]
how?

**Comment by AdriVanHoudt** [comment]
ok imagine creating an new entity on you API, the payload contains all the info from that entity. And you would do auth with a header so it does not get in the way

**Comment by Jiropole** [comment]
I have a similar question.. I think (hopefully not hijacking this recent thread). I have a mobile app that POSTs to a login route with a json object containing more data than I care to shove into the `Authorization` header, so I need to work with the payload in my auth scheme. After reading the docs several times on the `authentication` vs `payload` functions, and still don't understand the behavior I'm seeing. My scheme implementation returns `{ authenticate: internals.authenticate, payload: internals.payload, options: { payload: true } };`

First it hits `authenticate()` and I return `reply.continue(null, { credentials: {} });`. Next it hits `payload()`, but I have to do some asynchronous work here (calling out with Wreck). However, the moment the function returns, the reply is sent to the client, instead of waiting for the call to `reply.continue()` when the async call completes. I've been ramming my head against this for hours now, and feel like must be missing the obvious. I'll redact/post my code if necessary, but maybe this is an obvious blunder?

**Comment by mtharrison** [comment]
I'm pretty sure `return reply.continue(null, { credentials: {} });` in `authenticate` will throw an error. It says in the docs if authentication was successful:

> - `reply.continue(result)` - is called if authentication succeeded where:
     - `result` - same object as result above.

With `result` being:

> - `result` - an object containing:
     - `credentials` - the authenticated credentials.
     - `artifacts` - optional authentication artifacts.

So that should probably be: `reply.continue({ credentials: {} });`.

If that doesn't answer, we'll probably need to see your code.

**Comment by Jiropole** [comment]
I tried your suggestion, but the result is the same. So, my register code:
```
exports.register = function (server, options, next) {

    server.auth.scheme('hapi-auth-mobile', internals.implementation);
    next();
};
```
Implementation:
```
internals.implementation = function(server, options) {

    // <snip> options validation
    return { authenticate: internals.authenticate, payload: internals.authenticatePayload, options: { payload: true } };
};
```
Authenticate: `reply.continue({ credentials: {} });`

Payload:
```
internals.authenticate = function(request, reply) {

    // <snip> retrieve various auth data from payload and set up request options

    // send request
    Wreck.get(authUrl, requestOptions, function(err, res, payload) {
        if (err) {
            return reply(err);
        }

        if (res.statusCode > 299) {
            return reply(Boom.unauthorized(err));
        }

        request.auth.credentials = { 'credentials': { 'token': authToken, results: payload } };
        return reply.continue();
    });
};
```

So again, the issue is that when the `payload` function returns, the response goes out to the client immediately, as a 400 status with payload:
```
{
	"statusCode": 400,
	"error": "Bad Request"
}
```

**Comment by Jiropole** [comment]
I've experimented some more, and it definitely appears that while asynchronous operations are supported in the `authenticate` function, they are not supported in `payload`. Can anyone verify whether this is by design, or is a bug? Is there an alternative approach to verifying credentials in the payload? By the way, I was basing my original `authenticate` "skip-me" response according to [this earlier thread](https://github.com/hapijs/hapi/issues/2066), which must be outdated. Thanks!

**Comment by mtharrison** [comment]
I think you've got something else going on. You definitely can do async stuff in `payload`. What's in `internals.authenticate`. A 400 isn't an auth related response, are you sure there's not some validation error at play here?

**Comment by Jiropole** [comment]
```
internals.authenticate = function(request, reply) {
    // continue to allow payload authentication
    reply.continue({ credentials: {} });
}
```
So the only thing I want to do here is pass control to `payloadAuthenticate`. I have hapi-auth-cookie set up as the global auth scheme, with a `validateFunc` that never gets called (don't have a cookie yet) and then for my login route (my custom strategy is called 'mobile'):
```
    server.route({
        method: 'POST',
        path: '/auth/login',
        config: {
            auth: {
                mode: 'required',
                strategies: ['session', 'mobile']
            },
            handler: function (request, reply) {
                if (!request.auth.isAuthenticated) {
                    return reply(Boom.unauthorized('Authentication failed: ' + request.auth.error.message));
                }
                // <snip> set cookie in session cache, authenticate or register user, and send reply
           }
        }
    });
```

I'm definitely a beginner with Hapi, so its safe to say I don't have any sophisticated logic going on elsewhere. I have a few simple routes, but have been focused on getting authentication working. I was hoping to use Bell, but it seems to be geared toward web applications, or is such a black box I'm not sure how to use it with a mobile application that acquires validation tokens directly from providers.

**Comment by Jiropole** [comment]
You were right the problem was elsewhere. I was using the callback version of Joi.validate(), and misinterpreting the results to return a badRequest; this was responsible for sending the premature response. Sorry for wasting your time (and mine!)

**Comment by mtharrison** [comment]
There doesn't seem to be any issue here? @AdriVanHoudt @willin? Going to close, please reopen if I missed something.
