### ISSUE TITLE
Route request is not detecting the hash

### ISSUE THREAD

**Issue by grevory** [hapijs/hapi#3109]
`server.route({
  method: ['GET'],
  path: '/example',
  handler: function (request, reply) {
    reply(request.url.hash);
  }
});`

Then go to http://host.com/example#IAmAHash.

The value is empty.

**Comment by Marsup** [comment]
Hashes are never sent by browsers, that's not hapi's fault.

**Comment by grevory** [comment]
Some API use the hash for OAuth tokens. This makes Hapi completely incompatible with those APIs.

Why is it a part of `request.url` if it is always going to have no value?

**Comment by devinivy** [comment]
OAuth2 access tokens that come back in the hash are meant to be utilized by the user-agent (browser).  Browsers will never send hashes to the server– hapi doesn't even have the opportunity to use the hash.  The reason that `hash` appears on `request.url` is because node's [`Url.parse()`](https://nodejs.org/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost) includes the field in the object that it returns.

**Comment by Marsup** [comment]
Because an URL as a "type" is different from what's transmitted over the wire, usually server don't care for hashes since it's a client thing so it's not even sent, it seems weird to use it. If it's there it should be parsed and available to you.

**Comment by mtharrison** [comment]
The object `request.url` comes from Node built in url parsing function: https://nodejs.org/dist/latest-v4.x/docs/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost

**Comment by grevory** [comment]
Thanks guys

**Comment by mtharrison** [comment]
3 answers in the space of 20s. Can't ask for much more than that :smile:
