### ISSUE TITLE
Evaluate JSON.stringify() usage

### ISSUE THREAD

**Issue by leesei** [hapijs/hapi#3114]
Follow up on PR #3014 

- We can roll back that PR when [this](https://chromium.googlesource.com/v8/v8.git/+/26f617f1bc63e2b28bd9ea5f2146ad3a6b57396f) lands on Node v4 (the oldest supported version)
- ~~We should also try out [`fast-safe-stringify`](https://www.npmjs.com/package/fast-safe-stringify)~~ external dependency not preferred

A benchmark case should be built to check these issues, but hapi doesn't seem to have benchmarks, where to start?

**Comment by nlf** [comment]
benchmarking for things like this should be done with the smallest function possible, in this case JSON.stringify itself. doing benchmarks of a complex function is rarely helpful since you have little insight as to which calls are slowing things down. we could do things like use heat maps to figure it out, but for the entire framework that's a lot of effort.

IMO we shouldn't bother. benchmark the smallest functions you can outside of the framework. if you made it faster that way, then it'll make hapi faster too.
