### ISSUE TITLE
URL resolution order - specific before generic

### ISSUE THREAD

**Issue by vmendiratta** [hapijs/hapi#3123]
Hi

Can I register two routes/URLs like the following:

/api/v1/specific/status/
/api/v1/{generic}/status/

And handle them using two different handlers?

Will adding them in two separate plugins and making sure specific is registered before the generic be the way to go?

I'm sorry if this is a naïve question.

**Comment by devinivy** [comment]
It's not a naive question– different frameworks/routers totally handle this differently.  The hapi framework cares a lot about dealing with this sort of situation in order to make sure your server behaves predictably.

The order that routes are registered wont matter.  The router that hapi uses (call) is deterministic, and will simply throw an error if your routes conflict in an ambiguous way– so you'll know when something's wrong.  You should be able to register both of those routes with separate handlers in any order you desire, and the more specific route will always win exactly when you'd expect it to.

In the future, please open questions in [hapijs/discuss](https://github.com/hapijs/discuss).  Also feel free to open an issue over there if you'd like to continue this conversation.

**Comment by vmendiratta** [comment]
Thanks a lot. That helps a great deal. Hapi is making me extremely happy!
