### ISSUE TITLE
Deploying Hapi.js app to AWS EC2

### ISSUE THREAD

**Issue by aashishtripathi10** [hapijs/hapi#3183]
I am trying to deploy an app made in Hapi.js to AWS EC2 but I am unable to find any help online.

The app works perfect on localhost (I'm using Postman) but after deploying, I can't get a response to the requests even after I can see the server running in SSH/PuTTY.

Any help will be highly appreciated.

**Comment by devinivy** [comment]
You may need to adjust security groups so that the correct ports are open on your EC2 instance– namely, whichever port on which your hapi server listens.

In the future, discussions/questions like this are best placed in [discuss/hapijs](https://github.com/hapijs/discuss).  Feel free to to open an issue over there to continue the conversation!
