### ISSUE TITLE
use hapijs with html5 mode SPA

### ISSUE THREAD

**Issue by kfir124** [hapijs/hapi#3189]
how can I tell hapijs to serve index.html for any url?

or even better to serve it only when it fails to find a file? (when using the directory handler)

or to server it for any url that does not have .js .css .i_dontcare...

I want to use it to serve html5 mode urls but my assets are not in an assets folder I want something similar to nginx try_files

**Comment by mtharrison** [comment]
This is a usage question rather than an issue/improvement with hapi, so is better suited to [hapijs/discuss](https://github.com/hapijs/discuss), please continue the discussion there if you have more questions on this.

---

To serve index.html for any request (catch-all):

```js
server.route({
    method: '*',
    path: '/{p*}',
    handler: function (request, reply) {
        
        return reply.file(Path.join(__dirname, 'wherever/index.html'));
    }
});
```

> how can I tell hapijs to serve index.html for any url?
> or even better to serve it only when it fails to find a file? (when using the directory handler)

The above are basically the same because of the way hapi's router works. Define your index.html route as a catch-all as shown above, if you define a more specific route i.e. `path:  '/about'` that one will win.
