### ISSUE TITLE
k7 in the Hapi's org

### ISSUE THREAD

**Issue by thebergamo** [hapijs/hapi#3225]
Hi! 

Few months ago, I develop a module called k7, I want to transfer the ownership of k7 to the Hapi's organization, at this point, I'm developing some new updates and adapting the module to Hapi guideline, as you can see in the branch [v1.5](https://github.com/thebergamo/k7/tree/v1.5).

Following the link for the repo: https://github.com/thebergamo/k7

What is the next steps after all adjustments was completed?

**Comment by Marsup** [comment]
Not sure it's a good thing to "officially" endorse any data access layer pattern (however good), there are really many ways to do it and I wouldn't want this to become a defacto standard just because it's in the organization. What do others think ? (FTR this discussion should belong in contrib or discuss)

**Comment by devinivy** [comment]
I generally agree.  I also expect we will see certain patterns emerge for official plugins like this, where (in this case) models and databases should be able to be specified on a per-plugin level using realms.  This is consistent with the way vision works when assigning a views manager, for example.

**Comment by cjihrig** [comment]
The hapijs org shouldn't be a dumping ground for modules that people don't want to maintain anymore. We'd be on the hook for finding a lead maintainer, etc.

**Comment by thebergamo** [comment]
Sorry for open this discuss here, move to the right place!
