### ISSUE TITLE
CORS ISSUE IN HAPI JS

### ISSUE THREAD

**Issue by devendrakumar1007** [hapijs/hapi#3289]
Hi team,

I am getting the error in hapi js. 

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9080' is therefore not allowed access.

please team how to resovle and how to set the header in hapi js
header('Access-Control-Allow-Origin', '*');
header('access-control-allow-methods', 'GET,POST,PUT');
header('access-control-allow-headers', 'content-type');
 

Thanks & Regards,
Devendra

**Comment by mtharrison** [comment]
Can you please provide an example that fails? Ideally this would be a reduced version of the code that shows the issue, that we can then run and verify for ourselves? Otherwise it's difficult to debug your issue.

I can tell you though that you shouldn't need to set those headers manually, you can manage them through the [`cors` route config option](http://hapijs.com/api#route-configuration).

**Comment by devendrakumar1007** [comment]
Hi mtharrisom,

First thanks for your response.

My server.js file is
'use strict';

const Hapi = require('hapi');

// Create a server with a host and port
const server = new Hapi.Server();
server.connection({ 
    host: 'localhost', 
    port: 7777
});



var routeController={
 config: {
        cors: {
            origin: ['*'],
            additionalHeaders: ['cache-control', 'x-requested-with']
        }
    },

    method: 'GET',
    path:'/hello/{id}', 
    handler: function (request, reply) {
        //return reply('hello world kumar sahu'+request.params.id);
		return reply({"user":{"username": "devendra","password": "devendra"}});
    },
	
	  method: 'POST',
    path:'/authenticate/', 
    handler: function (request, res) {


	console.log('hit service');
     
		return res({ "success": true });
    }
	
	
}


// Add the route
server.route(
   routeController);

// Start the server
server.start((err) => {

    if (err) {
        throw err;
    }
    console.log('Server running at:', server.info.uri);
});

Server is running fine i am getting the response from POSTMAN and HTTP Request plugin.

But when i am calling this rest service by using angular js, then i am getting the error. 
angular js post method unable to hit the service. 

 Chrome Browser  error : XMLHttpRequest cannot load http://localhost:7777/authenticate/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9080' is therefore not allowed access


Angular Js request:
$http.post('http://localhost:7777/authenticate/', { username: username, password: password })
                .success(function (response) {
console.log('in side response');
                       });

**Comment by hueniverse** [comment]
Please post support issues in hapijs/discuss.

**Comment by waysay** [comment]
Having the same issue

`var server = new Hapi.Server({
        connections : {
            routes : {
                cors : {
                    origin : ['*'] // to allow API requests from our front end later
                }
            }
        }
    });`

**Comment by moyesh** [comment]
i have this issue too...

**Comment by LaszloA** [comment]
Same issue, exactly the same configuration. Could not understand why this issue is closed, since no solution was provided. The net is plenty of such complaints regarding this hapi server cors issue, (more than a year) still no solution. In my opinion, it is a shame that the authors and major contributors to this project (who are the firsts must react) did not find a clear, stable fix for this error. Or, at least, to tell us: "Sorry guys, we don't know what's happening!" or "Solve it yourself, or use another server!"

**Comment by vdeturckheim** [comment]
@LaszloA , I am sorry you feel that way. However as stated by @hueniverse on Aug 21:

> Please post support issues in [hapijs/discuss](https://github.com/hapijs/discuss).

Feel free to open an issue there and to share snippets of your code.

**Comment by LaszloA** [comment]
@vdeturckheim Hi Vladimir, thank you for your reply. First of all, I really appreciate the work the authors have done with hapi and not only with this. After all, I am using it, and it is free. The whole concept of the open source and free projects posting, like here on git, is remarkably generous. Thank you for all!

However, there are some very annoying tendencies regarding this domain, which, additionally, are  crescent in time. These are the selectivity lack between good, valorous, quality work and garbage, and the lack of exigency in updating and support. In my opinion, if somebody starts a project and invite other to use it, it is their duty then to keep it alive, answer questions and support it. This is true, even if this is an unpaid work. You have obligation regarding your followers, even if they give you no money to you. In my opinion, this is a matter of self-exigency. If you could not take this obligation, is better to do not start your public project at all. Worth to mention, by competent sources, more than 90% of the projects on git are garbage already. Of course, this is not the case of HAPI. Yet.

You see, we already discuss a lot, but the concrete problem is still not solved. Moving the discussion from one link to another does not solve the issue. Of course, I visited already the link you give me. From 162 open and 239 closed issues, only one is about CORS (not the problem we are discussing here), even if it is a very general issue more than a year ago starting from StackOverflow to Google Groups. It would be more lucrative to solve it finally than shepherd the interlocutors from one link to another.

I solved my private problem in another way. However if the authors consider that for a solution is needed to present this issue to this particular discussion group, then I will do it.

With respect, Laszlo

**Comment by Marsup** [comment]
Such a nice way to say "thanks" and "fuck you" at the same time. You clearly have a major contribution trail in open source so yeah please teach us how it's done. I think I feel comfortable asking you not to use hapi, ever, we don't need this kind of users. But since I value my time more than you seem to value it, I'll leave you with the [wise words of Eran](https://hueniverse.com/2016/01/26/how-to-use-open-source-and-shut-the-fuck-up-at-the-same-time/) on the matter. Yeah that's another link, it seems we're only good at that.

**Comment by LaszloA** [comment]
Hello, Nicolas!

Just not to send you to another site, Bernard Shaw said: "you mustn't be a hen to know if an egg is rotten".  It is under my dignity to reply to you with the tone and words it seems you are customized. You (and your cited friend) represent exactly the type of programmers who make a great disfavor for the open source community. 

Your mistake is, you think, anything you put here we must be grateful for it. Nor at all! Only if it is really useful, and the team is exigent, responsive and supporting. More users you have, bigger is your duty too.

You think this platform, git, is for showing your skills and expertise, without any responsibility. It is not. The whole software writing job is not a scope for itself. It  worths only if it is used. By others. So the users are an indispensable part of your work here. And yes, if you started this job, do it well, you are obligated to answer to your users, till you can. You could not pick only the issues you want, and leave the others. 

Of course, nobody can blame you if you couldn't find a solution. Nobody's perfect. No problem, but tell it, don't be elusive, don't ignore us. We'll wait then. Don't be rude, don't behave aggressively, and don't offense us if we raise a problem. We are your users, remember, our satisfaction is the ultimate goal of your work, or, at least, here it should be. In the other case, keep your code for you, enjoy in solitude how brilliant you are, nobody will contradict you. 

This platform is for exigent and helpful people and their users, it is not a stage for rude, maybe frustrated, exhibitionists. Your followers invest time (maybe money too) using your software, even if it is free, don't tell me now "use another server if you don't like my attitude, I have no mood to solve your problem". In my opinion, since you put something here, you are responsible for it, exactly as for a paid service. Just like a pro bono working advocate must do the same quality job as he/her should be paid. Why on earth, GitHub must be a wretched site? You and others like you made this platform highly unreliable and plenty of garbage. It would be beneficial if will remain only those 1/10 or even 1/100 projects I spoke about, but the quality would be 1000 times higher. 

In other words, in my opinion, this platform is for talented, skilled programmers who write good code for free and could support it as well. The fact they work pro bono is an additional thing, the cherry on the cake. It does not allow you to behave like a child on his private playground.

No, I haven't put any project on git or other platforms, exactly for this reason. Not because I have nothing to share, maybe more than you, but because I could not afford to support it well. I prefer to help people and exhibit my expertise in other ways, but professionally. In medicine, the first rule is: "Don't harm!".  Adapted to GitHub: "Don't create blur or spam, respect your users!". I guess, it is my right to ask the same behavior from you too. Frankly, I am sorry I integrated HAPI in my project, it took me two days googling for, then other two finding another, solution. Not speaking about the consumed nerves and the time for this unpleasant discussion. Seeing your attitude urgently will replace HAPI in totality. 

Apropos, as a shortcut, if I pay you, could you solve my (our) problem?

**Comment by AdriVanHoudt** [comment]
`In my opinion, since you put something here, you are responsible for it, exactly as for a paid service.`
This is simply not true. Putting code on Github doesn't come with any responsibilities. 
`It worths only if it is used.`
No. You can just put code here for fun/archive/...
`We are your users, remember, our satisfaction is the ultimate goal of your work, or, at least, here it should be. `
It is not and it should not be. hapi exists because someone needed something so they made it for themselves. The goal is purely selfish, to solve a problem Eran/his team had. They were so nice to open source it so other could benefit from it.
`Your mistake is, you think, anything you put here we must be grateful for it.`
Well of course you should. Someone did work to help you and to make your live easier FOR FREE. How can you not be grateful for that?
`This platform is for exigent and helpful people and their users, it is not a stage for rude, maybe frustrated, exhibitionists.`
It is also not for people thinking they are entitled to something they are not entitled to.

If you think Github is cluttered go talk to Github. If you don't like hapi, go use something else. If you think you're not good enough to put something public on Github you are clearly missing the point of it, and that is not this project's problem.
` if I pay you, could you solve my (our) problem?`
In general there would be a lot people wanting to help you if you pay them!
At this point I would be surprised though...

**Comment by jamesdixon** [comment]
@AdriVanHoudt amen!

@LaszloA please, stop. I'm actually embarrassed for you.

**Comment by nlf** [comment]
This issue has derailed pretty severely. I'm locking this thread. Contributors, I'm asking that you please stop engaging. This is going nowhere productive. @LaszloA if you'd like to discuss you can reach out to me personally on gitter.im
