### ISSUE TITLE
Requests failing somewhere between onRequest and onPreAuth

### ISSUE THREAD

**Issue by alexdrans** [hapijs/hapi#3376]
Hapi 15.2.0
Node 6.7

I'm encountering a bug whereby requests aren't hitting my handlers. The only sign of life I get from my requests is in the 'onRequest' hook, but nothing from 'onPreAuth' or beyond. I get no errors, and my requests time out with ERR_EMPTY_RESPONSE.

My question is.. how can I discover why it's failing? I'm getting no errors whatsoever. This suddenly started happening yesterday and is affecting my production code. I'm dumbfounded right now.

**Comment by AdriVanHoudt** [comment]
Let's see what can go wrong ![](https://pbs.twimg.com/media/CL-bp3_W8AAimRi.png:large)
Take a look at part A
It either isn't matching routes but then it should return a 404
It could be jsonp related (are you using this?)
It could be an error in the cookie parsing

Are you doing stuff on `onRequest` and maybe not giving control back to hapi when done?
Maybe something is swallowing the error?

Otherwise maybe look through http://stackoverflow.com/search?q=ERR_EMPTY_RESPONSE+node?

**Comment by alexdrans** [comment]
Thanks for the reply @AdriVanHoudt. I did take a look at the lifecycle. It fails on every single route I have, 'onRequest', and then nothing.

`server.ext('onRequest', (request, reply) => {
      console.log('onRequest'); // Gets hit
    });

    server.ext('onPreAuth', (request, reply) => {
      console.log('onPreAuth'); // This and below not hit
    });

    server.ext('onPostAuth', (request, reply) => {
      console.log('onPostAuth');
    });

    server.ext('onPreHandler', (request, reply) => {
      console.log('onPostAuth');
    });

    server.on('request-error', function (request, err) { 
      console.log(err);
    })`

**Comment by AdriVanHoudt** [comment]
You need to call `return reply.continue();` when done in your onRequest extension

**Comment by alexdrans** [comment]
Exact same result with `return reply.continue();` added 😞

**Comment by AdriVanHoudt** [comment]
And no jsonp and cookies?

**Comment by alexdrans** [comment]
jsonp is null on the request, and there are no cookies being sent AFAIK. API calls fail from both inside the app, and using Postman.

**Comment by alexdrans** [comment]
Issue seems to be a plugin. Thanks for rubber ducking @AdriVanHoudt.
