### ISSUE TITLE
let var in loop (question)

### ISSUE THREAD

**Issue by billouboq** [hapijs/hapi#3403]
It's more of a question than an issue.
Would like to know if it is wise to change let variable to var in for loop due to v8 not optimizing it ?

If it is I can make pull requests to change this.

**Comment by AdriVanHoudt** [comment]
I have heard about this but not sure about the details.

I think @cjihrig will know more about this.

Are you currently having perf problems with it?

**Comment by cjihrig** [comment]
There are cases where `var` is still faster than `let`. In general, `let` is still not used in Node core. However, if performance is not suffering, I'd recommend `let`, especially if it's already written that way. I just saw a notification today in core that this should be fixed in future versions of v8, but that won't be available in Node for a few more months.

**Comment by billouboq** [comment]
Nice, then no need to change it, thanks.
