### ISSUE TITLE
(Not Very) Dynamic scopes

### ISSUE THREAD

**Issue by TimMurnaghan** [hapijs/hapi#3425]
We are implementing a permissioning scheme - and scopes and dynamic scopes looked like an attractive way of doing it. But the restriction (by using Hoek reach) to only interpolating variables from params and queries makes it infeasible.

Here is one of our use cases. A resource "model" has a user who has locked it. The POST method should enforce that the requesting user is the locked user. 

I wanted to write something like:
```js
    auth: {
            scope: ['user-{model.getLockedUser(params.model_id)}']
        }
```
where model.getLockedUser is from our application code but, of course, that is invalid reach syntax.

Any non-trivial scheme is going to want to encapsulate the logic into functions - and permission can depend on things that aren't in the request - so could we look at interpolating things that aren't just variables from the request?

* *node version*:
v.4.5.0
* *hapi version*:
v 13.5.3
* *os*:
Windows 7

**Comment by vdeturckheim** [comment]
I am under the impression that such behavior would introduce a huge security issue. The client would be able to inject code that would be executed on the server.

Maybe introducing the possibility to have a function returning the scope could do the trick?

**Comment by AdriVanHoudt** [comment]
+1 for allowing scope to be a function that returns what is now allowed on scope

**Comment by gordysc** [comment]
What's stopping you from doing this in a pre-handler?

**Comment by AdriVanHoudt** [comment]
@gordysc if I am correct auth runs before the pre handlers
See ![](https://pbs.twimg.com/media/CL-bp3_W8AAimRi.png:large) by @mtharrison

**Comment by devinivy** [comment]
@TimMurnaghan I would suggest instead using the scope `user-from-lock`, and pushing the `model.getLockedUser()` business into your auth strategy.

**Comment by TimMurnaghan** [comment]
@vdeturckheim Just be clear. When I said application code - I meant server side, NOT part of the payload, so yes to the function returning the scope - that's what my snippet was meant to say.

@AdriVanHoudt It always good to be clear. This is about authorization, not authentication, so saying "auth" is ambiguous. While authentication does indeed happen early - I can't see why we couldn't make this authorization work in a pre-handler. But it's a bit of pain to have to - when what's already there is nearly what we want.

@gordysc I guess we could make it work by writing a pre-handler. After all that's how hapi-dynamic-scope was done before it was adopted into the core, it just feels like re-implementing stuff that had already been done.
It also ties us more deeply into the internals, and has to be weighed up against putting the authentication code into the handlers - which is where many programmers will feel more comfortable as there's less magic. Both of those options feel a bit wrong, which is why I raised this issue.

**Comment by TimMurnaghan** [comment]
@devinivy I had always though of the strategy as being authentication - as I say above - this is authorization so I'd rather not encourage that confusion by putting it there.

Putting that architecture concern to one side, the locked user depends on the model_id which is derived from the request url is that possible to to that kind of unpacking of the request in the strategy?

**Comment by AdriVanHoudt** [comment]
@TimMurnaghan I see that I misread the point ;)

making a custom strategy like @devinivy stated seems to be the best solution imo

And yes you have full access to the request and reply object (params are not validated yet though)

**Comment by devinivy** [comment]
Either way, your scheme/strategy is the thing that's responsible for handing-out scopes, and scopes are concerned with authorization.  If you really don't want to put it there, then writing an `onPostAuth` request extension rather than scopes would be another decent solution.

As far as updates to hapi go, I could imagine giving access to `request.app` and/or `request.plugins` within dynamic scope strings, and you could put anything in there you'd like (i.e. the result of a function).  I couldn't support scopes diving into `eval()` land!

**Comment by TimMurnaghan** [comment]
@devinivy Hmm. I guess I'm still searching for the right abstraction. 
In my view of the world the scopes that the authentication provider gives out are the identity related ones - i.e the permissions that the user has.

The authorization problem comes in generating the ones that the resource needs to match against the ones from the provider.  It seems a bit wrong to do that piece in the provider.

I wasn't really asking for eval land (OK - maybe the snippet was). How about a Promise based API?
 If you get a promise rather than a string in the scope array you call it to get the scope?

**Comment by gordysc** [comment]
@TimMurnaghan fair point.  I'm aware of the logic on the life cycle.  I've felt with the complexity and application specific nature of this I typically would handle post-auth in a prehandler/postAuth extension since it is "authorization" and not "authentication".   I could see where it might make some sense from a readability side of things, but it seems like you have the option at the moment, although it's not leveraging the "scope" option.

**Comment by AdriVanHoudt** [comment]
@gordysc yeah I misunderstood your first comment ^^

**Comment by gordysc** [comment]
Would regex be a potential compromise?

**Comment by hueniverse** [comment]
I am unlikely to add more complexity to scope processing of string literals. We are not reinventing eval. I am open to other approaches such as a "mid" auth extension that runs on the request before scope validation is done and then exposes some values in a special app space for use in scope strings.

That said, I think you are making things more complex than they should be. Dynamic scopes are really going further than the built-in system is designed to provide. You probably want to write your own plugin that does fancy scope matching. I know you would want to still use the `scope` config so maybe we add an external scope processor that is executed instead of the built-in one. They you can do whatever you want.

**Comment by TimMurnaghan** [comment]
@gordysc I don't think regexes help enough. The problem is that I want the permissions to depend on the existing resource state and not just the request variables - so no amount of formatting on those is going to do it.

@hueniverse I don't think that I'm trying to make this over complex. It's always worth seeing if you can make it work with the existing concepts before inventing new ones - and the idea of "external scope processor" is pretty close to what I was thinking if you put a function in the scope definition.
 But maybe you're right about the plugin/intermediate layer.  If I get some time I might look at it.

**Comment by tjsail33** [comment]
@TimMurnaghan you could try out https://github.com/mark-bradshaw/mrhorse for you desire to allow access to users based on params. I use it heavily on a project, and it sounds like it would handle that you want to do.
