### ISSUE TITLE
Feedbacks on core 'http2' module

### ISSUE THREAD

**Issue by mcollina** [hapijs/hapi#3584]
Can one of you check out the experimental 'http2' module from core?
The docs are here: https://nodejs.org/api/http2.html.

If would be good to know if we have to change anything to better support the integration with Hapi.

We plan to make `require('http2')` available without a flag in Node 9, and move it out of experimental before Node 10.

cc @jasnell

**Comment by hueniverse** [comment]
Probably another week before I can get into it with v17 in full dev right now.

**Comment by mcollina** [comment]
There is no hurry, just let us know here or open issues on nodejs/node.

**Comment by mnot** [comment]
Where's the best place to leave feedback / ask questions?

**Comment by mcollina** [comment]
Here or in nodejs/node.

**Comment by hueniverse** [comment]
@mnot about the node http2 module in general or it's relation with hapi?

**Comment by mnot** [comment]
In general; I'll give it over there. Thanks.

**Comment by hueniverse** [comment]
I don't see an HTTP2 native support happening in the near future as there are no clear use cases driving this. I know some people are using hapi with the new HTTP2 server but I don't really have enough experience to provide feedback. I hope this will change but I don't really want to build HTTP2 features without some kind of business driver...

**Comment by chrisdavies** [comment]
Hi @hueniverse I work on the Elastic Kibana team (but I don't claim to speak for them).

We've currently got a feature that uses websockets mostly because Hapi doesn't have http2 support. Basically, we've got a feature (Canvas) that allows our end-users to build fancy, custom scripted UIs. The scripting language generally needs to communicate with the server. So, if they build a UI with loads of little components, each with a custom script, it gets really chatty. This isn't ideal over HTTP/1, but HTTP/2 or websockets mitigates the problem.

I'd personally prefer to use HTTP/2 for this, as I think it would mean simpler code for us. Happy to discuss in more detail, if you're interested.

**Comment by hueniverse** [comment]
@chrisdavies feel free to ping me on the hapihour slack channel. I'd need more context to understand how you want to use http/2 with hapi.
