### ISSUE TITLE
route.options.response.modify

### ISSUE THREAD

**Issue by glebfeklistov** [hapijs/hapi#3938]
The "route.options.response.modify" not work on validate output payload.
Full example:
```js
const Joi = require('joi');
const Hapi = require('hapi');

process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

const server = Hapi.server({
    port: 3000,
    host: 'localhost'
});

server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
        return 'Hello, world!';
    }
});

server.route({
    method: 'GET',
    path: '/{name}',
    handler: (request, h) => {
        return 'Hello, ' + encodeURIComponent(request.params.name) + '!';
    }
});


const userInSchema = {
    username: Joi.string().min(1).max(20),
    password: Joi.string().min(7)
};

const userOutSchema = {
    username: Joi.string().min(1).max(20)
};

server.route({
    method: 'POST',
    path: '/signup',
    handler: function (request, h) {
        // console.log(request);
        return request.payload;
    },
    options: {
        auth: false,
        validate: {
            payload: userInSchema
        },
        response: {
            modify: true,
            schema: userOutSchema
        }
    }
});

server.start().then(() => {
    console.log(`Server running at: ${server.info.uri}`);
});
```

**Comment by aorinevo** [comment]
Hi @glebfeklistov,

What version of hapi and joi are you using?

**Comment by glebfeklistov** [comment]
Lastest and we already replace hapi to express solution. Thanks for long answer.

**Comment by hueniverse** [comment]
@glebfeklistov for the record, you clearly don't understand how to use joi. The modify option is used to make changed to the output based on the schema. But the schema you provided will just fail because `password` is present. There are no magic filters. joi can't read your mind and figure out that you want it to drop all keys no listed in your schema. It is also a terrible idea to use schema validation on output to sanitize security values from a response. The modify option is used for example, to turn strings in the response into numbers.

**Comment by glebfeklistov** [comment]
Ok, im use joi about two years, after you comment i think change to another great solution, may be JSON-SCHEMA.

**Comment by hueniverse** [comment]
That's a great idea!
