### ISSUE TITLE
Reconsider policy

### ISSUE THREAD

**Issue by rg4real** [hapijs/hapi#3954]
Your warning are all over the web and annoying. Please, reconsider this. I am not against you making money on open source. That is cool! But please consider the annoying part of your approach. 

Thanks!

**Comment by hueniverse** [comment]
If by annoying you mean telling people that the code they are using is no longer maintained, I’m cool with that.

**Comment by rg4real** [comment]
@hueniverse it's a nice way to say it to overcome my point and make me sound bad.

> If by annoying you mean telling people that the code they are using is no longer maintained, I’m cool with that.
No, I did not mean that. The message says just more. And what I am talking about is about the overall policy.

It's nice aim to be payed for an open source! Maybe github new feature will provide this project with some finances. I just hope other maintainers won't adopt your current strategy.

**Comment by hueniverse** [comment]
The deprecation messages have nothing to do with making money. They are meant to annoy you and make you stop using these versions as they are unsafe and unsupported. The fact they mention available commercial support is only logical since that is one option you have. They also list first your free option to just upgrade.

I don't know what your proposed solution is. Shorter messages that don't provide useful information about what you can do to resolve the problem? No messages at all, leaving you with security issues? That I keep supporting all versions forever because you don't want to be annoyed?

Seriously? What exactly do you think is the solution here?

And I didn't make you sound bad. It was your own attitude.
