### ISSUE TITLE
Support joi v16

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#3975]

**Comment by kanongil** [comment]
There will still be issues with the fix when composing. Eg. for:

```js
validate: {
    payload: {
        a: JoiNext.number(),
        b: JoiNext.array()
    })
}
```

So some care has to be taken to use a Joi object as the top-level option.

**Comment by Marsup** [comment]
As explained here: https://github.com/hapijs/joi/issues/2107#issuecomment-531543758.

**Comment by kalinkrustev** [comment]
Is this really part of @hapi/hapi@18.4.0, which was released before this change?
It is included in the changelog https://hapi.dev/resources/changelog/, but still published version at npm lists "@hapi/joi": "15.x.x" as dependency.

**Comment by hueniverse** [comment]
You have to wrap your top level object with `Joi.object()`.

**Comment by kalinkrustev** [comment]
Thanks, but I am not even trying to use joi. I am having some weird issue with npx trying to run a package than bundled hapi. It fails with some filesystem move operation. This is where I saw joi installed in several places due to hapi requiring 15.x.x. So I just wondered was this supposed to be bumped in hapi 18.4.0.

**Comment by hueniverse** [comment]
It was not.
