### ISSUE TITLE
Typescript types for hapi are incompatible with boom and iron

### ISSUE THREAD

**Issue by dbrockman** [hapijs/hapi#3979]
I got these errors after updating some of the packages in the hapi family

- `@hapi/boom` from 7.4.3 to 7.4.7
- `@hapi/iron` from 5.1.1 to 5.1.2

The problem seems to be that the types that `@types/hapi__hapi` imports from `@hapi/boom` and `@hapi/iron` are not compatible with the types that are now bundles with boom and iron.

- The version of `@types/hapi__hapi` is 18.2.5
- The version of `@hapi/hapi` is 18.4.0

Some of the interfaces that boom and iron used to export are no longer exported, such as `Output` from boom and `SealOptions` from iron.

```
node_modules/@types/hapi__hapi/index.d.ts:32:10 - error TS2305: Module '"node_modules/@hapi/iron/lib"' has no exported member 'SealOptions'.

32 import { SealOptions, SealOptionsSub } from '@hapi/iron';
            ~~~~~~~~~~~

node_modules/@types/hapi__hapi/index.d.ts:32:23 - error TS2305: Module '"node_modules/@hapi/iron/lib"' has no exported member 'SealOptionsSub'.

32 import { SealOptions, SealOptionsSub } from '@hapi/iron';
                         ~~~~~~~~~~~~~~

node_modules/@types/hapi__hapi/index.d.ts:514:32 - error TS2709: Cannot use namespace 'Boom' as a type.

514     response: ResponseObject | Boom;
                                   ~~~~

node_modules/@types/hapi__hapi/index.d.ts:4050:18 - error TS2709: Cannot use namespace 'Boom' as a type.

4050         (Error | Boom) |
                      ~~~~
```

**Comment by bricss** [comment]
@dbrockman It will be more reasonable to raise an issue about this here https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by Marsup** [comment]
We might solve it with https://github.com/hapijs/iron/pull/83 as it's going to be hard to solve in DT.

**Comment by dbrockman** [comment]
Yeah, I realize that the issue spans multiple repos and that bundling TS types is an ongoing work in progress... I wasn't sure if making a DefinitelyTyped PR would be a good idea if you are in the process of moving types into the hapi packages.

**Comment by hueniverse** [comment]
Closed upstream.

**Comment by dbrockman** [comment]
This is still broken in the exact same way. Please don't introduce breaking changes in patch releases. When you alter typescript interfaces in this way it should definitely be considered a breaking changes because it will break build steps in ways that are really hard to get around.

**Comment by hueniverse** [comment]
As far as I can see everything was changed to match the previous external definitions plus some actual bug fixes. If you still get errors with the latest then please provide specific errors so we can look into it. 

As a general note, this is going to be a bumpy process because we can’t do it all in one swoop and we are not going to do major releases on every types change. It’s just the nature of this work at this scale and complexity. I am going to try lifting all the DT files as is and moving them in as first step and see if that works to make consistent incremental changes easier. But at the end of the day I need to fix the many bugs in the current definitions and because TS is often half baked, this means moving a lot of stuff around to get the closest result. Latest changes to boom show that (ability to decorate an error in TS). 

Always looking for suggestions on how to do this better. Specific bug reports would be greatly appreciated.
