### ISSUE TITLE
Scoped package names in plugin dependencies

### ISSUE THREAD

**Issue by rgov** [hapijs/hapi#4088]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.9.1
* *module version*: 18.4.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application?
* *any other relevant information*:

#### How can we help?

I have a plugin which declares

```js
exports.plugin = {
  name: 'routes-api-cruises',
  dependencies: ['hapi-mongodb', '@hapi/nes'],  // <- there it is
  ...
}
```

When it runs, I fail [this assertion check](https://github.com/hapijs/hapi/blob/v18.3.0/lib/core.js#L342): `Error: Plugin routes-api-cruises missing dependency @hapi/nes`

What I discovered in debugging this is that in the  function `_validateDeps`, Hapi enumerates the dependencies declared by each plugin. It looks these up in `this.registrations`, a map of plugin registrations.

The keys in this map are *unscoped* package names, so instead of `@hapi/nes` there is just `nes`. If I update the plugin dependencies to just say `nes`, it works.

However, I am assuming that this works on the system of the person who wrote this code. Why does my system require unscoped package names? Is this documented anywhere?

**Comment by jonathansamines** [comment]
@rgov The reason is simple, older versions of some dependencies you are having issues with, used to have an override for it's name: take [@hapi/nes v11](https://github.com/hapijs/nes/blob/v11.2.1/lib/index.js#L93) as an example (the plugin renamed itself to `nes` even when the package is called `@hapi/nes`), latest version [@hapi/nes v12](https://github.com/hapijs/nes/blob/master/lib/index.js#L92) is no longer including such override.
