### ISSUE TITLE
server.inject does not reflect actual HTTP response in case of stream error

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi#4182]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 15.0.1
* *module version with issue*: 20.0.1
* *last module version without issue*: ?
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

When the response is a stream, and that stream generates an error at some point, the HTTP connection is "just" closed (with an incomplete response). This is kinda expected (although not tested in the code base). However, calling `server.inject()` with the same endpoint will show a `statusCode` that does not match the actual result (because headers where already sent when the error occured).

```js
const Stream = require('stream');

const Hapi = require('.');

const testStream = (chunks, highWaterMark = 1) => {

  return Stream.Readable.from(genBytes(), { objectMode: false, highWaterMark })

  async function* genBytes() {
      while (chunks--) {
        if (chunks === 1) throw new Error('Fake internal error')
        yield "1".repeat(highWaterMark)
      }
  }
}

const server = Hapi.server({
  port: 8080,
});

server.route({
  method: 'GET',
  path: '/',
  handler: (request, h) => {

      return h.response(testStream(10));
  }
});


server.start()

server.inject('/').then((response) => {
  const { headers, rawPayload, result, statusCode, statusMessage } = response
  console.log({ headers, rawPayload, result, statusCode, statusMessage })
  console.log(response.request.logs.length) // should not be 0
})

```

#### What was the result you got?

The following is printed to stdout (result of `server.inject`):
```
{
  headers: [Object: null prototype] {
    'content-type': 'application/octet-stream',
    'cache-control': 'no-cache',
    date: 'Sat, 07 Nov 2020 21:39:19 GMT',
    connection: 'keep-alive',
    'transfer-encoding': 'chunked'
  },
  rawPayload: <Buffer 31 31 31 31 31 31 31 31>,
  result: {
    statusCode: 500,
    error: 'Internal Server Error',
    message: 'An internal server error occurred'
  },
  statusCode: 500,
  statusMessage: 'OK'
}
0
```

However, when performing an HTTP request to http://127.0.0.1:8080/ yields:
```
HTTP/1.1 200 OK
content-type: application/octet-stream
cache-control: no-cache
Date: Sat, 07 Nov 2020 21:25:06 GMT
Connection: close
Transfer-Encoding: chunked

11111111

```

#### What result did you expect?

The status code of `server.inject()` should match the actual result, even in case of stream error.
Also: the `error` does not appear in the `response.request.logs` array (while still being emitted on the server's request `error` channel).

**Comment by devinivy** [comment]
I got to dive into this today and do a little research.  The reason for this behavior is actually not hard to pinpoint, and is even intentional: https://github.com/hapijs/hapi/blob/440850fac726dd3a9f60bc0875c55e378303ab8c/lib/transmit.js#L294-L308

This code always runs after the original status code and headers were written: it's meant to handle request/response close, abort, end, or stream errors while the response payload is being written.  The `if (request.raw.res[Config.symbol])` specifically targets the case that the request is injected, and you can see the `statusCode` being rewritten there.  This code and behavior has some history: https://github.com/outmoded/discuss/issues/729 https://github.com/hapijs/hapi/issues/3561 

I appreciate your point here, which is why I labeled it as a bug.  But I also see why these decisions were made in the past, so it's hard to decide how to proceed.  While the response does say "200", this response also essentially failed, and an HTTP client should report the request as having failed.  Here's how curl reports it:
```
curl: (18) transfer closed with outstanding read data remaining
```


In my opinion `inject()`'s `response.statusCode` _should_ be changed to match the status code you'd find if you e.g. made a request through node's http client and checked your `IncomingMessage`'s `statusCode`.  However, `inject()` should leave `response.result` as-is.  With that change, when `response.result` is an error then `response.statusCode` might be `200` while `response.result.statusCode` would be `500` in a case of a stream error, or `499` in case of a disconnection.  This would better preserve all information about what occurred (i.e. the original `200` status code), and it would bring `inject()`'s behavior more in-line with a typical http client.  It would also be a breaking change to hapi.

Let's see what folks think.  @kanongil you were part of the original discussion in https://github.com/outmoded/discuss/issues/729— do you have any feelings?

> Also: the error does not appear in the `response.request.logs` array

I was not able to reproduce this issue.  However, I did have to turn on log collection by configuring my route with `{ log: { collect: true } }`.

> When the response is a stream, and that stream generates an error at some point, the HTTP connection is "just" closed (with an incomplete response). This is kinda expected (although not tested in the code base).

I think this test is the one intended to cover it: https://github.com/hapijs/hapi/blob/440850fac726dd3a9f60bc0875c55e378303ab8c/test/transmit.js#L703

**Comment by devinivy** [comment]
Alright, I think this is a reasonable way to handle this, particularly without making any breaking changes: https://github.com/hapijs/hapi/pull/4191

  - Now `server.inject()`'s `response.raw.res.statusCode` is never overwritten.  This will read `200` in the case reported above.  Prior to the fix it read `500`.
  - Now `server.inject()`'s `response.statusMessage` remains in sync with `response.statusCode`.  This will read `'Internal Server Error'` in the case reported above.  Prior to the fix it read `'OK'`.

**Comment by matthieusieben** [comment]
I'm glad I raised a valid point. Sorry about my incorrect statements in my initial message.
