### ISSUE TITLE
Hapi.js support for node 14 and above 

### ISSUE THREAD

**Issue by vinaya-thimmappa** [hapijs/hapi#4193]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no 
* *is this issue affecting a production system?* (yes/no): no 

#### Context

* *node version*:  14.15.0
* *module version*: 
* *environment* (e.g. node, browser, native): node 
* *used with* (e.g. hapi application, another framework, standalone, ...):hapi application
* *any other relevant information*:
         > NODE_CONFIG_DIR=config node --max_old_space_size=1024 server.js
but nothing comes up. 

if I move to node version 12.14.0, it works fine. 
but with    
node version 14.15.0 (this is LTS)  and above (even 15+) nothing works. 

my hapi version is 
  "@hapi/hapi": "^20.0.2",

i did get fibers issue

#### How can we help?
any pointers to fix the above would really help us. Otherwise, I would be stuck with node version 12

**Comment by cjihrig** [comment]
Without more information I'm going to say this is almost certainly an issue with your application. All of the modules under the hapijs GitHub org are tested on Node 14.

**Comment by devinivy** [comment]
> i did get fibers issue

I will add that if you're talking about this module https://github.com/laverdet/node-fibers, then it does seem highly dependent on the nodejs version and isn't tested above node v12, whereas hapi is well-supported and -tested on node v14.  Your next step might be to look into your usage of fibers rather than of hapi.  If you can provide some debugging information and it points to hapi I will happily take another look 👍
