### ISSUE TITLE
Please help me to make it work!

### ISSUE THREAD

**Issue by jbarros35** [hapijs/hapi#4202]
I'm trying to make my single page app using angular to work, the last step is making the routing to work.
The only hope I found was on this thread
https://stackoverflow.com/questions/55577601/how-to-get-routing-to-work-in-hapijs-angular

Well the code provided cannot compile on the current version of your lib!
Should I ask help to whom? Its very frustrating believe me...

My main issues right now is based on this couple of code cant compile because the thread its too old... its hard to believe nobody want to do that!
```

this.server.ext('onPreResponse', (request, h) => {
            const response = request.response;
        
            if (!response.isBoom) {
              return h.continue;
            }
        
            if (response.output.statusCode === 404) {
              return h.file('index.html');
            }
          });
```

```

[ERROR] 23:30:05 ⨯ Unable to compile TypeScript:
src/app.ts:71:27 - error TS2339: Property 'isBoom' does not exist on type 'Boom<any> | ResponseObject'.
  Property 'isBoom' does not exist on type 'ResponseObject'.

71             if (!response.isBoom) {
                             ~~~~~~
src/app.ts:75:26 - error TS2339: Property 'output' does not exist on type 'Boom<any> | ResponseObject'.
  Property 'output' does not exist on type 'ResponseObject'.

75             if (response.output.statusCode === 404) {
                            ~~~~~~
src/app.ts:76:24 - error TS2339: Property 'file' does not exist on type 'ResponseToolkit'.

76               return h.file('index.html');

```
Sorry I had really nobody to ask for clarifications anymore...

#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### How can we help?

```js
const some = 'properly formatted code example';
```

**Comment by devinivy** [comment]
I am going to close this out because it doesn't follow the issue template, and the issue you're running into seems to be related to typescript usage rather than hapi usage.  A search for your typescript error turned this up, though, and perhaps it will be useful to you: https://stackoverflow.com/questions/54184444/how-to-fix-typescript-error-property-isboom-does-not-exist-on-type-boomany.  You can also join the hapi hour slack, which has a #typescript channel for further community support: https://join.slack.com/t/hapihour/shared_invite/zt-g5ortpsk-ErlnRA2rUcPIWES21oXBOg
