### ISSUE TITLE
Hosting nodejs API (with hpai server) in IIS

### ISSUE THREAD

**Issue by Shameer1163** [hapijs/hapi#4233]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):No
* *is this issue affecting a production system?* (yes/no):No

#### Context

* *node version*:  latest
* *module version*: latest
* *environment* (e.g. node, browser, native): Windows with IIS
* *used with* (e.g. hapi application, another framework, standalone, ...):node js API with mssql module using hpai server
* *any other relevant information*:

#### How can we help?
I have a nodejs api using hpai framework to retrieve data from sql using mssql module. This works fine from VS Code, i am wondering if there is an option to host this in IIS and what would be the steps to do that?

```js
const some = 'properly formatted code example';
```

**Comment by Marsup** [comment]
I guess you're going to want to use https://github.com/Azure/iisnode but I have no idea how it works, that's a bit outside of the scope of this project, I'd go to them for documentation and/or help.

**Comment by Nargonath** [comment]
You can ask your question on our Community Slack channel @Shameer1163, perhaps someone has experience with it and could guide you regarding this. I have no experience with IIS either. You can find a link to join our Slack here: https://hapi.dev/support/. You could also ask your question on StackOverflow.

I'm closing this issue since it is not a problem with `hapi` itself.
