### ISSUE TITLE
Blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource Issue

### ISSUE THREAD

**Issue by robert-kopec** [hapijs/hapi#4237]
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 10.x
* *module version*: 18.4.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): Used by a front end React app
* *any other relevant information*: 

Hi, since last Friday, I have been getting the following headers errors both in development and production when fetching data from the backend HAPI API. The front end react app is primarily used in a tab inside Microsoft Teams (I think that uses Chromium), however the same issue happens when accessed in Chrome. 

Those errors are very irregular, it can throw an error when fetching an API call, and when I reload the page it works fine. Sometimes, it will not happen for 20/30 minutes then start happening again.

> Access to XMLHttpRequest at 'https://...' from origin 'http://....' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

The original HAPI server configuration already includes the CORS to be set to true and it never seemed to cause problems before:

```js
const server = Hapi.server({
    port: config.serverPort,
    routes: {
        cors: true
    },
});
```

I tried looking up similar issues and tried the following configuration:

```js
const server = Hapi.server({
    port: config.serverPort,
    routes: {
        cors: {
            origin: ['*'], // an array of origins or 'ignore'
            headers: ['Accept', 'Authorization', 'Content-Type', 'If-None-Match', 'Accept-language'], // all default apart from Accept-language
            additionalHeaders: ['cache-control', 'x-requested-with', 'Access-Control-Allow-Origin']
        }
    },
});
```

**Comment by Nargonath** [comment]
The `v18` is not under the responsibility of the TSC and is covered under commercial license. If you have subscribed to one you can perhaps contact Eran otherwise I'll suggest you ask your question on our Slack channel. I'm sure you can find help among the community. You can find a link to join on our website: https://hapi.dev/support/.

It's hard to tell what could go wrong in here. Perhaps try to share the request/response headers so we can better see what's going on in Slack. 😉

**Comment by devinivy** [comment]
Just wanted to add— while of course it's possible that hapi may be causing the issue, from the info presented here there are also several other options.  Since this issue presented itself more recently than there have been any changes to hapi v18, I think that it is possible that a change to Chromium could be the cause (in particular— is the app in a [content script / extension](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches) to be used as a "tab" in Teams?).  Infrastructure between your hapi server and the client is another option.  Finally, it stood out to me that the request is across schemes from http to https, and I read that Teams utilizes iframes for tabs.  There's a lot going on here from a browser/security perspective.  In any case, a great next step for debugging will be to catch a full request and response that exhibits this issue (i.e. including all headers).  If you have a minimal example that someone could run to reproduce the issue, that always helps too.  CORS can be really tricky, best of luck!

**Comment by ekaitzht-n26** [comment]
@robert-kopec could you fix this issue?

**Comment by robert-kopec** [comment]
Hi, the issue was actually not anything to do with Hapi, which I was very happy about as I thought I would have to upgrade to newest version which introduced many breaking changes. The problem was with nginx ingress controllers which control traffic coming into the API, somehow they have bugged out and simply restarting all of them fixed the issue.

**Comment by castrolle** [comment]
Hi, put a console print to check the rule on file cors.js:

cors.js
` if (headers) {
        headers = headers.toLowerCase().split(/\s*,\s*/);
      console.log(settings._headers);
      console.log(headers);
      console.log(Hoek.intersect(headers, settings._headers));
        if (Hoek.intersect(headers, settings._headers).length !== headers.length) {
            return { message: 'CORS error: Some headers are not allowed' };
        }
    }`

![2023-01-26 14 22 12](https://user-images.githubusercontent.com/3730836/214930493-d1692566-bd3f-47c3-999e-5999dcfddd06.png)
