### ISSUE TITLE
Issue multiple cookies with same name in response.

### ISSUE THREAD

**Issue by iamparnab** [hapijs/hapi#4245]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v10.23.2
* *module version*: 16
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): 
* *any other relevant information*:

#### How can we help?

I have one cookie in my browser with domain `xyz.abc.com`. Now in the next request I want to expire this cookie and set another cookie with same name with domain `abc.com`. I am able to do it using vanilla nodejs. This app is hosted on `xyz.abc.com`
```
res.setHeader("Set-Cookie", [
      "test=old;expires=Thu, 01 Jan 1970 10:00:00 GMT;path=/;domain=xyz.abc.com", // Expire
      "test=new;expires=Thu, 01 Jan 2070 00:00:00 GMT;path=/;domain=abc.com", // Re-issue
]);
```    
As per my understanding Hapi uses this cookie name to update its state. So, if I issue another cookie with same name then previous cookie is overwritten.

So, is it possible to achieve this goal?

**Comment by devinivy** [comment]
If you use `response.state()` or `h.state() to set the cookies then yes, that's right: the cookies are uniquely set by name.  However, you can also set the `set-cookie` header yourself using `response.header()` to achieve this.  It supports an `append` option so that you can call it multiple times to add to the same header.  hapi also allows you set the `set-cookie` header directly while also using `response.state()`, so these two approaches are not mutually exclusive.  Finally, you could use the [statehood](https://github.com/hapijs/statehood) module directly in order to generate the cookie headers with the same config that you can use with `response.state()`.

**Comment by iamparnab** [comment]
Thanks for the input. Is this solution same for v17 ?
Is it possible to provide documentation on `statehood` module?

**Comment by devinivy** [comment]
Yeah, I believe the solution should be identical for v17.  We'd certainly accept PRs for documentation on statehood, and for the interim the tests are a pretty good resource.  The main options for statehood are those documented in hapi's `server.state()` docs: https://hapi.dev/api/?v=20.1.2#server.state().

**Comment by iamparnab** [comment]
Hey @devinivy thanks for this information. The `response.header()` approach may work for me, but can I use this approach from `onPreAuth` extension?
Currently, I am able to it from `onPreResponse`. I am setting cookies by doing,  `request.response.header()`

**Comment by devinivy** [comment]
Yeah, it's true— in order to set a header, a response does already need to be set.  You may have to write a plugin to achieve what you're trying to do: you can place header information on `request.app` or within `request.plugins` at any point of the request lifecycle, then have an `onPreResponse` extension which actually applies them to the response (which must exist at that point in the lifecycle).  Here's an example:

```js
// The decoration and extension below could be wrapped into their own plugin for lazy header functionality.
// If it is in a plugin, consider using `request.plugins` rather than `request.app`.

server.decorate('toolkit', 'lazyHeader', function (name, value) {
  const h = this;
  h.request.app.lazyHeaders = h.request.app.lazyHeaders || [];
  h.request.app.lazyHeaders.push({ name, value });
});

server.ext('onPreResponse', (request, h) => {
  (request.app.lazyHeaders || []).forEach(({ name, value }) => {
    // In order to handle when request.response is an error, see @hapipal/toys header() utility
    request.response.header(name, value, { append: true });
  });
  return h.continue;
});

// Application code 

server.ext('onPreAuth', (request, h) => {
  h.lazyHeader('set-cookie', 'a=b');
  return h.continue;
});
```
