### ISSUE TITLE
GridFS Stream with HapiJS

### ISSUE THREAD

**Issue by YuenEsc** [hapijs/hapi#4252]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):yes
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: v14.15.1
* *module version*: 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):hapi,mongodb,mongoose
* *any other relevant information*:

#### How can we help?

I'm trying to connect Hapi with the library GridFS-stream from mongo to be able to store files on mongodb so far I was able to stream the files to the database but I am not able to read them.
I have seen implementations with express and replies about these issue on previous version of hapi that have breaking changes
Here is the code I have now. 
At this point it returns data, but I don't know in which format or how to proceed
```
const Grid = require('gridfs-stream');
const FileType = require('file-type');
const { Readable } = require('stream');
const { Homework } = require('../../models');

const Handler = {
  readHomeworkFile: {
    handler: async (request, h) => {
      const gfs = Grid(Mongoose.connection.db);

      const readStream = gfs.createReadStream({
        _id: request.params.id,
        root: 'homeworkFile',
      });

      readStream.on('error', (error) => {
        console.log(error);
      });
      // console.log(readStream);
      // return readStream.pipe(request.raw.res);
      return h.response(readStream)
        .type('text/event-stream')
        .header('Connection', 'keep-alive')
        .header('Content-Encoding', 'none')
        .header('Cache-Control', 'no-cache');
    },
  },
};

module.exports = Handler;
```

**Comment by Nargonath** [comment]
As far as I can tell, it doesn't seem to be a problem with `hapi` itself but rather something on your side. It's hard to tell what goes wrong here, perhaps you need to provide more options to `gfs.createReadStream`. One thing you could do first is try to write the stream you get from `gfs` into a file on your filesystem. If it doesn't work or you can't read the resulting file then it's most likely a problem with the `gfs` lib or the way you use it. Then once you're able to have a usable file on your FS then you can proceed and send the stream back to the client IMO.

I suggest you also try to post a message on our community Slack. Everyone is very welcoming there and perhaps someone would be able to help you further. You can find a link to join here: https://hapi.dev/support/. I'm going to close this for now since it's not a problem with `hapi` from what I can tell.
