### ISSUE TITLE
message: "code" is not allowed, stack: ValidationError: "code" is not allowed

### ISSUE THREAD

**Issue by vollaregroup** [hapijs/hapi#4317]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):no
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: v14.15.4
* *module version*: "@hapi/hapi": "^20.0.1",
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):standalone
* *any other relevant information*:

#### How can we help?

```js
const some = 'properly formatted code example';
```
there has been (apparently randomly) internal error 500:
  message: "code" is not allowed, stack: ValidationError: "code" is not allowed
I am unable to discover the source of this error.
Can someone help me ?

**Comment by devinivy** [comment]
This is almost certainly caused by some application code.  Do you use joi validation anywhere in your project?  It seems likely that joi is involved here because it looks like a`ValidationError` generated by joi.  In order to get more help, sharing some relevant code from your project would be very useful.  It would also be useful to see the URL, headers, and payload of the request made to your hapi server, and the headers and payload of the response.

**Comment by vollaregroup** [comment]
Thanks for the quick response.
Thats correct, I use Joi to validate headers and payload. I'll take a closer look at may code.
