### ISSUE TITLE
Support Vite dev mode

### ISSUE THREAD

**Issue by brillout** [hapijs/hapi#4369]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): <b>no</b>.
* *is this issue affecting a production system?* (yes/no): <b>no</b>.

#### Context

* *node version*: `18.0.0`
* *module version*: `20.2.2`
* *environment* (e.g. node, browser, native): `node`
* *used with* (e.g. hapi application, another framework, standalone, ...): [Vite](https://vitejs.dev/) and [vite-plugin-ssr](https://vite-plugin-ssr.com/)
* *any other relevant information*: none

#### What problem are you trying to solve?

Goal: use hapi with Vite and vite-plugin-ssr.

Vite's development middleware is a connect middleware, but hapi doesn't support connect middlewares (https://github.com/hapijs/hapi/issues/80).

(The vite-plugin-ssr integration works fine since vite-plugin-ssr's "middleware" is just a function.)

#### Do you have a new or modified API suggestion to solve the problem?

I'm not sure if there is an alternative than to have hapi support connect middlewares.

Although a workaround is to use two servers in development (hapi server for backend + Vite's development server for frontend). More information about this setup at https://vite-plugin-ssr.com/hapi.

**Comment by Nargonath** [comment]
I don't foresee hapi using middlewares at any point in time since that's basically one of its core principle. Since you want to do SSR, you might want to look into https://github.com/hapijs/inert. It's hapi's plugin to work with template engine and server-side rendering. Maybe there is something you can do to hook the middleware into it.

**Comment by kanongil** [comment]
Just keep using the regular vite dev server solution. Hapi is never going to support connect/express.js middleware.

If you really need it to be served by the same server in development, you could probably proxy requests to the vite dev server using https://github.com/hapijs/h2o2. Feel free to create a plugin that standardises this.

Closing since this is really just a request to support middlewares.

**Comment by devinivy** [comment]
You can mount an express server onto a hapi server using hecks: https://github.com/hapipal/hecks

**Comment by brillout** [comment]
Makes sense. Thanks for the insightful answers.

**Comment by jches** [comment]
> If you really need it to be served by the same server in development, you could probably proxy requests to the vite dev server

Posting here to add that you can also [configure the Vite dev server](https://vitejs.dev/config/server-options.html#server-proxy) to proxy requests to your Hapi server. It's built-in to vite and doesn't require any changes on the Hapi side: https://vitejs.dev/config/server-options.html#server-proxy. 

If you use [hapijs/nes](https://github.com/hapijs/nes) for websockets, it might conflict with Vite's hot-reload feature; in that case you can configure vite to use a different port for HMR: https://vitejs.dev/config/server-options.html#server-hmr
