### ISSUE TITLE
Get all session values

### ISSUE THREAD

**Issue by joshlsullivan** [hapijs/hapi#4371]
After setting multiple session values, is it possible to get all of the values at once, instead of calling `get` on individual sessions?

**Comment by devinivy** [comment]
hapi doesn't have the concept of a session— are you using the [yar](https://github.com/hapijs/yar) plugin, by chance?  If so, then I do not believe there is an API to get all the values at once, and you would have to call `yar.get()` for each key on the session.

**Comment by joshlsullivan** [comment]
Yes, I meant yar. What if I don't know the key? I'm trying to create a shopping cart and store the values of the cart in the session.

**Comment by devinivy** [comment]
I'd suggest restructuring your session so that the top-level key is something like `cartItems`, and underneath that is the list of items.  Actually you do have one other option, which is to use `request.yar.lazy(true)`, which places the keys directly on the `request.yar` decoration.  This has some additional implications, though, which you can more read about in the [yar docs](https://hapi.dev/family/yar/).  Hope this helps!

**Comment by joshlsullivan** [comment]
The lazy approach is a good idea. I tried it but didn't work. I really appreciate your feedback.

`const itemName = payload.name;`
`request.yar.itemName = payload`
`itemName: [Object: null prototype] {
    quantity: '12',
    name: 'Personal Training',
    variationItemId: 'Z32QC7WHGOKGOR4G5BUUY7QU',
    variationId: '7UEURIZFR46BO6GQTI6KDXGG',
    itemId: 'Z32QC7WHGOKGOR4G5BUUY7QU',
    taxId: '',
    itemPk: '2'
  }`
