### ISSUE TITLE
Hapi + Boom - Which types I should assign to error?

### ISSUE THREAD

**Issue by robzeltz** [hapijs/hapi#4393]
I use hapi + boom, but I don't know which types I should add to error.
At the moment my code look likes:
```
  } catch (error: any) {
    return Boom.badImplementation(error.message);
  }
```

What types is error? And where I can found information about it?

**Comment by Nargonath** [comment]
The type of your error here will depend on the source of it. If it comes from an error you didn't raise yourself then it's probably gonna be an `Error`. But if you raised a Boom error yourself e.g:

```ts
const user = await fetchUserInDb("user-123");

if (!user) {
  throw Boom.notFound();
}
```

Then your error will be a Boom error. You need to use a Type Guard in TypeScript to narrow down the type of a variable you receive as `unknown` or `any`. If you're not familiar with the concept you can read more about it here: https://www.typescriptlang.org/docs/handbook/advanced-types.html. Also luckily for you Boom already provide a type guard for you to use: https://hapi.dev/module/boom/api/?v=10.0.0#isboomerr-statuscode.

I'm closing this issue since it's not a problem with hapi itself but feel free to continue the discussion if you still have problem.
