### ISSUE TITLE
Opensearch dashboard. {   "statusCode": 413,   "error": "Request Entity Too Large",   "message": "Payload content length greater than maximum allowed: 1048576" }

### ISSUE THREAD

**Issue by HansamalDharmananda** [hapijs/hapi#4427]
When I try to add a bulk index to my "Opensearch" dashboard It overflows the limit. 
How can I increase the size of the payload?
I downloaded the [docker-compose.yml](https://www.opensearch.org/downloads.html) file from opensearch official web site.

**Comment by Nargonath** [comment]
Since you're using OpenSearch, if they decided to use `hapi` I bet it's abstracted away from you. You probably don't have access to the hapi configuration directly. In my opinion, you should look into OpenSearch documentation if they have a configuration setting that impacts hapi's route setting on payload max size: https://hapi.dev/api/?v=21.3.0#-routeoptionspayloadmaxbytes. You should probably open a ticket in their community forum or something like that.

If you were to use a bare hapi server then if you need to increase the allowed payload size for a specific route, you can use the setting I linked above.

I'm going to close this issue because I don't think it's hapi's responsibility but rather how OpenSearch configures their `hapi` servers. Feel free to reopen the issue if you have more information that would indicate there is something wrong on our side.
