### ISSUE TITLE
Request support for HEAD routes

### ISSUE THREAD

**Issue by fredrikwidlund** [hapijs/hapi#795]
In the case that a GET verb is expensive, HEAD is very useful to check the existence of a REST resource.

**Comment by vitaliyAtSvarog** [comment]
Guis i need HEAD to, for implementing tus.io protocol server based on hapijs. https://github.com/tus/tus-node-server - see example here.

**Comment by miksago** [comment]
As far as I know, HEAD is just GET but with the instruction to return headers only, and not the body of the response.

**Comment by jishi** [comment]
Saying that HEAD is just a GET without body is an oversimplification. The main usage of HEAD is to check for content freshness, and rarely includes the same logic as the actual GET in itself. To me it would make sense to at least allow one to separate them easily and more clearly than by checking the verb manually in the GET header. 

True though that it at least is possible, but gives you a very ugly code path and looks more like a hack rather than something you want to do.

**Comment by zyrorl** [comment]
I think closing this ticket is the wrong way of approaching this. There should be a way to add HEAD requests, and if a "GET" also creates a "HEAD", then this should be overridden by config, or at least over-written when one is separately specified.

**Comment by hueniverse** [comment]
The issue is whether this use case justifies adding the lookup complexity for every head request to first check for a custom override before looking up the GET route. I decided it is not worth it. Between your code being a tiny bit ugly to everyone else's run time performing additional look ups, I choose the former.
